"""Documentation for ALE Wizard of Wor (2-Player)."""
from __future__ import annotations

WIZARD_OF_WOR_HTML = (
    "<h3>ALE: Wizard of Wor (2-Player)</h3>"
    "<p>Dungeon crawler shooter for two players. Navigate mazes, destroy monsters, "
    "and battle the Wizard of Wor. Can be cooperative or competitive.</p>"
    "<h4>Make (Two-Player)</h4>"
    "<pre><code>from pettingzoo.atari import wizard_of_wor_v3\n"
    "env = wizard_of_wor_v3.parallel_env()</code></pre>"
    "<h4>Players</h4>"
    "<ul>"
    "<li><strong>Number of agents:</strong> 2</li>"
    "<li><strong>Agent IDs:</strong> <code>first_0</code>, <code>second_0</code></li>"
    "</ul>"
    "<h4>Action Space</h4>"
    "<p><code>Discrete(10)</code></p>"
    "<ul>"
    "<li>Movement in 4 directions</li>"
    "<li>Fire in 4 directions</li>"
    "<li>No operation</li>"
    "<li>Fire (default direction)</li>"
    "</ul>"
    "<h4>Observation Space</h4>"
    "<p><code>Box(0, 255, (210, 160, 3), uint8)</code> - RGB image</p>"
    "<h4>Game Mechanics</h4>"
    "<ul>"
    "<li>Navigate dungeon corridors</li>"
    "<li>Shoot monsters before they shoot you</li>"
    "<li>Some monsters turn invisible (use radar)</li>"
    "<li>Clear all monsters to advance to next dungeon</li>"
    "<li>The Wizard appears in later levels</li>"
    "</ul>"
    "<h4>Rewards</h4>"
    "<ul>"
    "<li>Destroy monster: points based on type</li>"
    "<li>Clear dungeon: wave bonus</li>"
    "<li>Kill the Wizard: large bonus</li>"
    "</ul>"
    "<h4>Game Types</h4>"
    "<ul>"
    "<li><strong>Cooperative:</strong> Clear dungeons together</li>"
    "<li><strong>Competitive:</strong> Score more than your partner</li>"
    "</ul>"
    "<h4>Game Type</h4>"
    "<p><strong>Mixed</strong> - Cooperative or competitive dungeon crawling.</p>"
    "<p>Docs: <a href='https://pettingzoo.farama.org/environments/atari/wizard_of_wor/'>"
    "PettingZoo: Wizard of Wor</a></p>"
)

__all__ = ["WIZARD_OF_WOR_HTML"]
