"""Documentation for ALE Quadrapong (4-Player)."""
from __future__ import annotations

QUADRAPONG_HTML = (
    "<h3>ALE: Quadrapong (4-Player)</h3>"
    "<p>A four-player team-based Pong variant where players control paddles to defend "
    "scoring areas while coordinating with their teammate.</p>"
    "<h4>Make (Four-Player)</h4>"
    "<pre><code>from pettingzoo.atari import quadrapong_v4\n"
    "env = quadrapong_v4.parallel_env()</code></pre>"
    "<h4>Players</h4>"
    "<ul>"
    "<li><strong>Number of agents:</strong> 4</li>"
    "<li><strong>Team 1:</strong> <code>first_0</code>, <code>third_0</code></li>"
    "<li><strong>Team 2:</strong> <code>second_0</code>, <code>fourth_0</code></li>"
    "</ul>"
    "<h4>Action Space</h4>"
    "<p><code>Discrete(6)</code></p>"
    "<ul>"
    "<li>0: No operation</li>"
    "<li>1: Fire (serve)</li>"
    "<li>2: Move up</li>"
    "<li>3: Move right</li>"
    "<li>4: Move left</li>"
    "<li>5: Move down</li>"
    "</ul>"
    "<h4>Observation Space</h4>"
    "<p><code>Box(0, 255, (210, 160, 3), uint8)</code> - RGB image</p>"
    "<h4>Game Mechanics</h4>"
    "<ul>"
    "<li>Each player defends one scoring area</li>"
    "<li>Ball moves across the court; teams coordinate to direct it toward opponents' zones</li>"
    "<li>Timed serves: Must serve within 2 seconds or team loses 1 point</li>"
    "</ul>"
    "<h4>Rewards</h4>"
    "<ul>"
    "<li>Score on opponent: <strong>+1</strong> reward for your team</li>"
    "<li>Opponent scores: <strong>-1</strong> reward</li>"
    "<li>Fail to serve in time: <strong>-1</strong> reward</li>"
    "</ul>"
    "<h4>Game Type</h4>"
    "<p><strong>Team Competitive</strong> - 2v2 team-based gameplay.</p>"
    "<p>Docs: <a href='https://pettingzoo.farama.org/environments/atari/quadrapong/'>"
    "PettingZoo: Quadrapong</a></p>"
)

__all__ = ["QUADRAPONG_HTML"]
