"""Documentation for ALE Combat Tank (2-Player)."""
from __future__ import annotations

COMBAT_TANK_HTML = (
    "<h3>ALE: Combat Tank (2-Player)</h3>"
    "<p>Two-player tank battle in maze-like arenas. Destroy your opponent's tank "
    "while navigating obstacles. Features various arena configurations and modes.</p>"
    "<h4>Make (Two-Player)</h4>"
    "<pre><code>from pettingzoo.atari import combat_tank_v2\n"
    "env = combat_tank_v2.parallel_env()</code></pre>"
    "<h4>Players</h4>"
    "<ul>"
    "<li><strong>Number of agents:</strong> 2</li>"
    "<li><strong>Agent IDs:</strong> <code>first_0</code>, <code>second_0</code></li>"
    "</ul>"
    "<h4>Action Space</h4>"
    "<p><code>Discrete(18)</code> - Full Atari action set including:</p>"
    "<ul>"
    "<li>Move forward/backward</li>"
    "<li>Rotate tank</li>"
    "<li>Fire cannon</li>"
    "</ul>"
    "<h4>Observation Space</h4>"
    "<p><code>Box(0, 255, (210, 160, 3), uint8)</code> - RGB image</p>"
    "<h4>Game Mechanics</h4>"
    "<ul>"
    "<li>Navigate through maze-like arenas</li>"
    "<li>Line up shots around obstacles</li>"
    "<li>Shells bounce off walls (in some modes)</li>"
    "<li>Tank movement is tank-style (rotate then move)</li>"
    "</ul>"
    "<h4>Rewards (Zero-Sum)</h4>"
    "<ul>"
    "<li>Destroy opponent: <strong>+1</strong> reward</li>"
    "<li>Get destroyed: <strong>-1</strong> reward</li>"
    "</ul>"
    "<h4>Arena Types</h4>"
    "<ul>"
    "<li>Open battlefield</li>"
    "<li>Maze with walls</li>"
    "<li>Invisible tanks mode</li>"
    "</ul>"
    "<h4>Game Type</h4>"
    "<p><strong>Competitive</strong> - Tank combat.</p>"
    "<p>Docs: <a href='https://pettingzoo.farama.org/environments/atari/combat_tank/'>"
    "PettingZoo: Combat Tank</a></p>"
)

__all__ = ["COMBAT_TANK_HTML"]
