"""Documentation for ALE Maze Craze (2-Player)."""
from __future__ import annotations

MAZE_CRAZE_HTML = (
    "<h3>ALE: Maze Craze (2-Player)</h3>"
    "<p>A competitive game of memory and planning where players race to escape a maze. "
    "Features three game versions with increasing complexity.</p>"
    "<h4>Make (Two-Player)</h4>"
    "<pre><code>from pettingzoo.atari import maze_craze_v3\n"
    "env = maze_craze_v3.parallel_env()</code></pre>"
    "<h4>Players</h4>"
    "<ul>"
    "<li><strong>Number of agents:</strong> 2</li>"
    "<li><strong>Agent IDs:</strong> <code>first_0</code>, <code>second_0</code></li>"
    "</ul>"
    "<h4>Action Space</h4>"
    "<p><code>Discrete(18)</code> - Full Atari action set including movement, fire, "
    "and combined actions</p>"
    "<h4>Observation Space</h4>"
    "<p><code>Box(0, 255, (250, 160, 3), uint8)</code> - RGB image</p>"
    "<h4>Game Versions</h4>"
    "<ul>"
    "<li><strong>Race:</strong> Basic version - first player to exit wins</li>"
    "<li><strong>Robbers:</strong> Features 2 randomly traversing robbers; "
    "capture results in -1 reward and elimination</li>"
    "<li><strong>Capture:</strong> Must capture all 3 robbers before exiting; "
    "includes ability to create deceptive blocks</li>"
    "</ul>"
    "<h4>Parameters</h4>"
    "<ul>"
    "<li><code>game_version</code>: \"race\", \"robbers\", or \"capture\"</li>"
    "<li><code>visibility_level</code>: 0-3 (0 = fully visible, 3 = completely hidden map)</li>"
    "</ul>"
    "<h4>Rewards</h4>"
    "<ul>"
    "<li>Exit maze first: <strong>+1</strong> reward</li>"
    "<li>Other player exits first: <strong>-1</strong> reward</li>"
    "<li>Captured by robber (Robbers mode): <strong>-1</strong> and eliminated</li>"
    "</ul>"
    "<h4>Game Type</h4>"
    "<p><strong>Competitive</strong> - Race to escape the maze.</p>"
    "<p>Docs: <a href='https://pettingzoo.farama.org/environments/atari/maze_craze/'>"
    "PettingZoo: Maze Craze</a></p>"
)

__all__ = ["MAZE_CRAZE_HTML"]
