"""Documentation snippets for Gymnasium MuJoCo environments."""

from __future__ import annotations

MUJOCO_REQUIREMENTS_HTML = (
    "<h4>MuJoCo Requirements</h4>"
    "<ul>"
    "<li>Install the Gymnasium extras with <code>pip install gymnasium[mujoco]</code>."
    "</li>"
    "<li>Install the MuJoCo engine (open-sourced by DeepMind) and set the "
    "appropriate <code>MUJOCO_GL</code> backend for headless use when needed.</li>"
    "<li>Older <code>mujoco-py</code> based environments live in "
    "<code>gymnasium-robotics</code>; use <code>pip install "
    "gymnasium_robotics[mujoco-py]</code> if you must reproduce legacy runs.</li>"
    "<li>Manual control is not wired into the GUI—launch these environments via "
    "an agent/worker (e.g., the CleanRL worker) and stream telemetry instead.</li>"
    "</ul>"
)

ANT_HTML = (
    "<h3>Ant-v5 (MuJoCo)</h3>"
    "<p>Coordinate an eight-legged quadruped to sprint forward without "
    "tumbling. Rewards combine forward velocity, alive bonus, and small "
    "penalties for joint torques and impact forces.</p>"
    "<h4>Observation</h4>"
    "<p>Flattened MuJoCo state: joint positions/velocities (qpos/qvel), body "
    "orientation, and contact sensor channels.</p>"
    "<h4>Action space</h4>"
    "<p>Continuous torque commands for eight motors in "
    "<code>[-1, 1]</code>.</p>"
    "<h4>Episode end</h4>"
    "<ul>"
    "<li>Termination: body height drops below the healthy threshold or "
    "magnitude of orientation diverges.</li>"
    "<li>Truncation: default time limit of 1000 steps.</li>"
    "</ul>"
    "<h4>Notes</h4>"
    "<ul>"
    "<li>Initial state is sampled with Gaussian noise to encourage robust "
    "policies.</li>"
    "<li>Customize dynamics via <code>xml_file</code> overrides (e.g., "
    "ant.xml variants) in Gymnasium.</li>"
    "</ul>"
) + MUJOCO_REQUIREMENTS_HTML

HALF_CHEETAH_HTML = (
    "<h3>HalfCheetah-v5 (MuJoCo)</h3>"
    "<p>Control a planar two-dimensional quadruped to accelerate along the "
    "forward axis. The agent must balance thrust and stability across six "
    "actuated joints.</p>"
    "<h4>Observation</h4>"
    "<p>Concatenated joint angles/velocities plus torso orientation; velocity "
    "is measured in the simulator frame.</p>"
    "<h4>Action space</h4>"
    "<p>Six continuous torque values in <code>[-1, 1]</code>.</p>"
    "<h4>Rewards</h4>"
    "<ul>"
    "<li>Forward velocity bonus.</li>"
    "<li>Control cost proportional to squared torque.</li>"
    "</ul>"
    "<h4>Episode end</h4>"
    "<ul>"
    "<li>No explicit termination—episode only truncates at the horizon (typically 1000 steps).</li>"
    "</ul>"
    "<h4>Notes</h4>"
    "<ul>"
    "<li>Popular benchmarking task for policy-gradient and actor-critic "
    "algorithms.</li>"
    "<li>Supports <code>exclude_current_positions_from_observation</code> "
    "argument for reproducibility with older results.</li>"
    "</ul>"
) + MUJOCO_REQUIREMENTS_HTML

HOPPER_HTML = (
    "<h3>Hopper-v5 (MuJoCo)</h3>"
    "<p>Maintain a forward-moving one-legged hopper with three controllable "
    "joints (torso, thigh, leg). Balance and thrust must be coordinated to "
    "avoid catastrophic falls.</p>"
    "<h4>Observation</h4>"
    "<p>Joint positions/velocities, torso orientation, and ground contact "
    "flags.</p>"
    "<h4>Action space</h4>"
    "<p>Three torque commands in <code>[-1, 1]</code>.</p>"
    "<h4>Episode end</h4>"
    "<ul>"
    "<li>Termination: torso height below threshold or absolute orientation "
    "beyond acceptable range.</li>"
    "<li>Truncation: default horizon of 1000 steps.</li>"
    "</ul>"
    "<h4>Notes</h4>"
    "<ul>"
    "<li>Alive bonus encourages staying upright; forward progress bonus drives "
    "learning speed.</li>"
    "<li>Great for testing balance-focused controllers.</li>"
    "</ul>"
) + MUJOCO_REQUIREMENTS_HTML

HUMANOID_HTML = (
    "<h3>Humanoid-v5 (MuJoCo)</h3>"
    "<p>Manage a high-dimensional human-like biped with 17 actuated joints. "
    "The goal is to travel forward quickly while staying upright.</p>"
    "<h4>Observation</h4>"
    "<p>Large flattened vector of joint positions, velocities, body "
    "orientation, and center-of-mass information.</p>"
    "<h4>Action space</h4>"
    "<p>17 continuous torque controls in <code>[-1, 1]</code>.</p>"
    "<h4>Episode end</h4>"
    "<ul>"
    "<li>Termination: center of mass height falls below threshold or agent "
    "tips excessively.</li>"
    "<li>Truncation: default 1000-step horizon.</li>"
    "</ul>"
    "<h4>Notes</h4>"
    "<ul>"
    "<li>Among the most challenging MuJoCo benchmarks; reward includes alive "
    "bonus, forward velocity, and small control costs.</li>"
    "<li>Requires careful reward normalization to keep learning stable.</li>"
    "</ul>"
) + MUJOCO_REQUIREMENTS_HTML

HUMANOID_STANDUP_HTML = (
    "<h3>HumanoidStandup-v5 (MuJoCo)</h3>"
    "<p>Teach a prone humanoid to stand upright. Rewards focus on increasing "
    "the center of mass height and maintaining balance.</p>"
    "<h4>Observation</h4>"
    "<p>Same high-dimensional state representation as Humanoid-v5.</p>"
    "<h4>Action space</h4>"
    "<p>17 torque commands in <code>[-1, 1]</code>.</p>"
    "<h4>Episode end</h4>"
    "<ul>"
    "<li>Termination: center of mass height drops too low or the agent "
    "collapses.</li>"
    "<li>Truncation: default horizon of 1000 steps.</li>"
    "</ul>"
    "<h4>Notes</h4>"
    "<ul>"
    "<li>Used to evaluate control policies that require staged objectives "
    "(stand-up first, then balance).</li>"
    "<li>Combines alive bonus with a large reward for gaining height.</li>"
    "</ul>"
) + MUJOCO_REQUIREMENTS_HTML

INVERTED_DOUBLE_PENDULUM_HTML = (
    "<h3>InvertedDoublePendulum-v5 (MuJoCo)</h3>"
    "<p>Stabilize a cart with two interconnected pendulum links. Keep both "
    "links upright while minimizing cart displacement.</p>"
    "<h4>Observation</h4>"
    "<p>Cart position/velocity plus joint angles and angular velocities for "
    "both links.</p>"
    "<h4>Action space</h4>"
    "<p>Single continuous cart force in <code>[-1, 1]</code>.</p>"
    "<h4>Rewards</h4>"
    "<ul>"
    "<li>Alive bonus while links remain within the upright envelope.</li>"
    "<li>Penalties for cart displacement and angular deviation.</li>"
    "</ul>"
    "<h4>Episode end</h4>"
    "<ul>"
    "<li>Termination: links fall beyond the allowed angle or cart position "
    "exceeds limits.</li>"
    "<li>Truncation: default time limit of 1000 steps.</li>"
    "</ul>"
) + MUJOCO_REQUIREMENTS_HTML

INVERTED_PENDULUM_HTML = (
    "<h3>InvertedPendulum-v5 (MuJoCo)</h3>"
    "<p>Classic control task: keep a single pendulum balanced upright on a "
    "moving cart by applying lateral forces.</p>"
    "<h4>Observation</h4>"
    "<p>Cart position/velocity and pole angle/angular velocity.</p>"
    "<h4>Action space</h4>"
    "<p>Single continuous force command in <code>[-1, 1]</code>.</p>"
    "<h4>Episode end</h4>"
    "<ul>"
    "<li>Termination: pole angle or cart position exceeds safe bounds.</li>"
    "<li>Truncation: default 1000-step horizon.</li>"
    "</ul>"
    "<h4>Notes</h4>"
    "<ul>"
    "<li>Regression target for MuJoCo control algorithms—simpler than the "
    "double pendulum but still sensitive to controller latency.</li>"
    "</ul>"
) + MUJOCO_REQUIREMENTS_HTML

PUSHER_HTML = (
    "<h3>Pusher-v5 (MuJoCo)</h3>"
    "<p>Manipulate a 7-DOF arm to push a cylinder toward a target on the "
    "tabletop. Rewards favor proximity to the target and penalize distance "
    "between the end-effector and object.</p>"
    "<h4>Observation</h4>"
    "<p>Joint positions/velocities, object position, and target marker "
    "location.</p>"
    "<h4>Action space</h4>"
    "<p>Seven torque commands in <code>[-1, 1]</code>.</p>"
    "<h4>Episode end</h4>"
    "<ul>"
    "<li>No early termination; episodes truncate at 100 steps by default.</li>"
    "</ul>"
    "<h4>Notes</h4>"
    "<ul>"
    "<li>Requires precise arm coordination and is sensitive to reward "
    "shaping.</li>"
    "<li>Useful for testing goal-conditioned policies.</li>"
    "</ul>"
) + MUJOCO_REQUIREMENTS_HTML

REACHER_HTML = (
    "<h3>Reacher-v5 (MuJoCo)</h3>"
    "<p>Guide a planar two-joint arm to reach a randomly placed goal marker. "
    "Small control costs encourage efficient movement.</p>"
    "<h4>Observation</h4>"
    "<p>Joint angles/velocities, end-effector position, and target location.</p>"
    "<h4>Action space</h4>"
    "<p>Two torque commands in <code>[-1, 1]</code>.</p>"
    "<h4>Episode end</h4>"
    "<ul>"
    "<li>Truncation after 50 steps; no early termination.</li>"
    "</ul>"
    "<h4>Notes</h4>"
    "<ul>"
    "<li>Great for verifying low-latency policy updates and reward tracking.</li>"
    "<li>Observation can optionally exclude absolute positions for "
    "reproducibility with older versions.</li>"
    "</ul>"
) + MUJOCO_REQUIREMENTS_HTML

SWIMMER_HTML = (
    "<h3>Swimmer-v5 (MuJoCo)</h3>"
    "<p>Move a three-link robot through a viscous fluid environment using two "
    "actuated joints. Policies learn to produce sine-like undulations.</p>"
    "<h4>Observation</h4>"
    "<p>Joint positions/velocities, body orientation, and linear velocity.</p>"
    "<h4>Action space</h4>"
    "<p>Two torque controls in <code>[-1, 1]</code>.</p>"
    "<h4>Rewards</h4>"
    "<ul>"
    "<li>Forward velocity bonus minus control cost.</li>"
    "</ul>"
    "<h4>Episode end</h4>"
    "<ul>"
    "<li>Episodes truncate at 1000 steps; no early termination.</li>"
    "</ul>"
    "<h4>Notes</h4>"
    "<ul>"
    "<li>Lower-dimensional dynamics make it a gentle introduction to "
    "continuous control with MuJoCo.</li>"
    "</ul>"
) + MUJOCO_REQUIREMENTS_HTML

WALKER2D_HTML = (
    "<h3>Walker2d-v5 (MuJoCo)</h3>"
    "<p>Control a planar two-legged biped with six actuated joints to walk "
    "forward while maintaining stability.</p>"
    "<h4>Observation</h4>"
    "<p>Joint angles/velocities, torso orientation, and ground contact "
    "sensors.</p>"
    "<h4>Action space</h4>"
    "<p>Six torque commands in <code>[-1, 1]</code>.</p>"
    "<h4>Episode end</h4>"
    "<ul>"
    "<li>Termination: torso height or angle leaves the healthy range.</li>"
    "<li>Truncation: default 1000-step limit.</li>"
    "</ul>"
    "<h4>Notes</h4>"
    "<ul>"
    "<li>Bridges the difficulty between Hopper and Humanoid—commonly used for "
    "benchmarking actor-critic methods.</li>"
    "</ul>"
) + MUJOCO_REQUIREMENTS_HTML

__all__ = [
    "MUJOCO_REQUIREMENTS_HTML",
    "ANT_HTML",
    "HALF_CHEETAH_HTML",
    "HOPPER_HTML",
    "HUMANOID_HTML",
    "HUMANOID_STANDUP_HTML",
    "INVERTED_DOUBLE_PENDULUM_HTML",
    "INVERTED_PENDULUM_HTML",
    "PUSHER_HTML",
    "REACHER_HTML",
    "SWIMMER_HTML",
    "WALKER2D_HTML",
]
