"""Documentation for ALE Tennis (2-Player)."""
from __future__ import annotations

TENNIS_HTML = (
    "<h3>ALE: Tennis (2-Player)</h3>"
    "<p>Full-court tennis game for two players. Uses standard tennis scoring with "
    "serve, volley, and ground stroke mechanics. Players must win by 2 games.</p>"
    "<h4>Make (Two-Player)</h4>"
    "<pre><code>from pettingzoo.atari import tennis_v3\n"
    "env = tennis_v3.parallel_env()</code></pre>"
    "<h4>Players</h4>"
    "<ul>"
    "<li><strong>Number of agents:</strong> 2</li>"
    "<li><strong>Agent IDs:</strong> <code>first_0</code>, <code>second_0</code></li>"
    "</ul>"
    "<h4>Action Space</h4>"
    "<p><code>Discrete(18)</code> - Full Atari action set including:</p>"
    "<ul>"
    "<li>Movement in all directions</li>"
    "<li>Swing racket (fire button)</li>"
    "<li>Combined movement + swing actions</li>"
    "</ul>"
    "<h4>Observation Space</h4>"
    "<p><code>Box(0, 255, (210, 160, 3), uint8)</code> - RGB image</p>"
    "<h4>Game Mechanics</h4>"
    "<ul>"
    "<li>Serve to start each point</li>"
    "<li>Return the ball over the net</li>"
    "<li>Ball must land in bounds</li>"
    "<li>Standard tennis scoring (15, 30, 40, game)</li>"
    "</ul>"
    "<h4>Rewards (Zero-Sum)</h4>"
    "<ul>"
    "<li>Win a point: <strong>+1</strong> reward</li>"
    "<li>Lose a point: <strong>-1</strong> reward</li>"
    "</ul>"
    "<h4>Game Type</h4>"
    "<p><strong>Competitive</strong> - Classic tennis match.</p>"
    "<p>Docs: <a href='https://pettingzoo.farama.org/environments/atari/tennis/'>"
    "PettingZoo: Tennis</a></p>"
)

__all__ = ["TENNIS_HTML"]
