"""Documentation for ALE Combat Plane (2-Player)."""
from __future__ import annotations

COMBAT_PLANE_HTML = (
    "<h3>ALE: Combat Plane (2-Player)</h3>"
    "<p>Two-player aerial dogfight with World War I biplanes. Engage in air combat "
    "maneuvering to get behind your opponent and shoot them down.</p>"
    "<h4>Make (Two-Player)</h4>"
    "<pre><code>from pettingzoo.atari import combat_plane_v2\n"
    "env = combat_plane_v2.parallel_env()</code></pre>"
    "<h4>Players</h4>"
    "<ul>"
    "<li><strong>Number of agents:</strong> 2</li>"
    "<li><strong>Agent IDs:</strong> <code>first_0</code>, <code>second_0</code></li>"
    "</ul>"
    "<h4>Action Space</h4>"
    "<p><code>Discrete(18)</code> - Full Atari action set including:</p>"
    "<ul>"
    "<li>Directional controls (turn, climb, dive)</li>"
    "<li>Fire machine guns</li>"
    "<li>Thrust/speed control</li>"
    "</ul>"
    "<h4>Observation Space</h4>"
    "<p><code>Box(0, 255, (210, 160, 3), uint8)</code> - RGB image</p>"
    "<h4>Game Mechanics</h4>"
    "<ul>"
    "<li>Maneuver your biplane in 2D space</li>"
    "<li>Get behind opponent for clean shots</li>"
    "<li>Avoid being shot down</li>"
    "<li>Wrap around screen edges</li>"
    "</ul>"
    "<h4>Rewards (Zero-Sum)</h4>"
    "<ul>"
    "<li>Shoot down opponent: <strong>+1</strong> reward</li>"
    "<li>Get shot down: <strong>-1</strong> reward</li>"
    "</ul>"
    "<h4>Game Modes</h4>"
    "<ul>"
    "<li>Standard dogfight</li>"
    "<li>Invisible planes mode</li>"
    "<li>Cloud cover obstacles</li>"
    "</ul>"
    "<h4>Game Type</h4>"
    "<p><strong>Competitive</strong> - Aerial combat.</p>"
    "<p>Docs: <a href='https://pettingzoo.farama.org/environments/atari/combat_plane/'>"
    "PettingZoo: Combat Plane</a></p>"
)

__all__ = ["COMBAT_PLANE_HTML"]
