"""Documentation for ALE Joust (2-Player)."""
from __future__ import annotations

JOUST_HTML = (
    "<h3>ALE: Joust (2-Player)</h3>"
    "<p>Aerial combat on flying ostriches (or storks). Defeat enemies by colliding "
    "with them from above. Can be played cooperatively or competitively.</p>"
    "<h4>Make (Two-Player)</h4>"
    "<pre><code>from pettingzoo.atari import joust_v3\n"
    "env = joust_v3.parallel_env()</code></pre>"
    "<h4>Players</h4>"
    "<ul>"
    "<li><strong>Number of agents:</strong> 2</li>"
    "<li><strong>Agent IDs:</strong> <code>first_0</code>, <code>second_0</code></li>"
    "</ul>"
    "<h4>Action Space</h4>"
    "<p><code>Discrete(18)</code> - Full Atari action set including:</p>"
    "<ul>"
    "<li>Horizontal movement</li>"
    "<li>Flap wings to gain altitude</li>"
    "<li>Combined movement + flap</li>"
    "</ul>"
    "<h4>Observation Space</h4>"
    "<p><code>Box(0, 255, (210, 160, 3), uint8)</code> - RGB image</p>"
    "<h4>Game Mechanics</h4>"
    "<ul>"
    "<li>Flap to fly - gravity pulls you down</li>"
    "<li>Collide with enemies from above to defeat them</li>"
    "<li>Collect eggs before they hatch into new enemies</li>"
    "<li>Avoid lava and pterodactyl</li>"
    "</ul>"
    "<h4>Rewards</h4>"
    "<ul>"
    "<li>Defeat enemy: points based on enemy type</li>"
    "<li>Collect egg: bonus points</li>"
    "<li>Survive wave: wave completion bonus</li>"
    "</ul>"
    "<h4>Game Types</h4>"
    "<ul>"
    "<li><strong>Cooperative:</strong> Work together against AI enemies</li>"
    "<li><strong>Competitive:</strong> Battle each other for higher score</li>"
    "</ul>"
    "<h4>Game Type</h4>"
    "<p><strong>Mixed</strong> - Cooperative or competitive gameplay.</p>"
    "<p>Docs: <a href='https://pettingzoo.farama.org/environments/atari/joust/'>"
    "PettingZoo: Joust</a></p>"
)

__all__ = ["JOUST_HTML"]
