"""Documentation for ALE Double Dunk (2-Player)."""
from __future__ import annotations

DOUBLE_DUNK_HTML = (
    "<h3>ALE: Double Dunk (2-Player)</h3>"
    "<p>Two-on-two basketball game featuring dunking mechanics. Each player controls "
    "a team with passing, shooting, stealing, and slam dunk capabilities.</p>"
    "<h4>Make (Two-Player)</h4>"
    "<pre><code>from pettingzoo.atari import double_dunk_v3\n"
    "env = double_dunk_v3.parallel_env()</code></pre>"
    "<h4>Players</h4>"
    "<ul>"
    "<li><strong>Number of agents:</strong> 2</li>"
    "<li><strong>Agent IDs:</strong> <code>first_0</code>, <code>second_0</code></li>"
    "</ul>"
    "<h4>Action Space</h4>"
    "<p><code>Discrete(18)</code> - Full Atari action set including:</p>"
    "<ul>"
    "<li>Movement in 8 directions</li>"
    "<li>Shoot/steal (fire button)</li>"
    "<li>Combined movement + action</li>"
    "</ul>"
    "<h4>Observation Space</h4>"
    "<p><code>Box(0, 255, (210, 160, 3), uint8)</code> - RGB image</p>"
    "<h4>Game Mechanics</h4>"
    "<ul>"
    "<li>Move players to the basket</li>"
    "<li>Pass between teammates</li>"
    "<li>Shoot or dunk to score</li>"
    "<li>Steal the ball on defense</li>"
    "</ul>"
    "<h4>Rewards (Zero-Sum)</h4>"
    "<ul>"
    "<li>Score a basket: <strong>+2</strong> reward</li>"
    "<li>Opponent scores: <strong>-2</strong> reward</li>"
    "</ul>"
    "<h4>Game Type</h4>"
    "<p><strong>Competitive</strong> - Fast-paced basketball action.</p>"
    "<p>Docs: <a href='https://pettingzoo.farama.org/environments/atari/double_dunk/'>"
    "PettingZoo: Double Dunk</a></p>"
)

__all__ = ["DOUBLE_DUNK_HTML"]
