"""Documentation for PettingZoo Connect Four."""
from __future__ import annotations


def get_connect_four_html(env_id: str = "connect_four_v3") -> str:
    """Generate Connect Four HTML documentation."""
    return (
        "<h3>PettingZoo: Connect Four (connect_four_v3)</h3>"
        "<p>Classic Connect Four game where players alternate dropping colored discs into "
        "a 7-column, 6-row grid. First player to connect four discs in a row "
        "(horizontal, vertical, or diagonal) wins. Simple rules but strategically deep.</p>"
        "<h4>Environment Details</h4>"
        "<ul>"
        "<li><strong>Import:</strong> <code>from pettingzoo.classic import connect_four_v3</code></li>"
        "<li><strong>API Type:</strong> AEC (turn-based)</li>"
        "<li><strong>Parallel API:</strong> Yes</li>"
        "<li><strong>Agents:</strong> ['player_0', 'player_1']</li>"
        "<li><strong>Action Shape:</strong> Discrete(7)</li>"
        "<li><strong>Observation Shape:</strong> (6, 7, 2)</li>"
        "<li><strong>Observation Values:</strong> [0, 1]</li>"
        "</ul>"
        "<h4>Observation Space</h4>"
        "<p>6×7×2 binary tensor representing the board state:</p>"
        "<ul>"
        "<li><strong>Channel 0:</strong> Current player's pieces (1 where player has disc)</li>"
        "<li><strong>Channel 1:</strong> Opponent's pieces (1 where opponent has disc)</li>"
        "</ul>"
        "<p>The board is indexed [row][column] where row 0 is the bottom row.</p>"
        "<h4>Action Space</h4>"
        "<p>Discrete(7) - each action drops a disc into the corresponding column (0-6):</p>"
        "<ul>"
        "<li><strong>Action 0:</strong> Drop disc in leftmost column</li>"
        "<li><strong>Action 1-5:</strong> Drop disc in columns 1-5</li>"
        "<li><strong>Action 6:</strong> Drop disc in rightmost column</li>"
        "</ul>"
        "<p>The disc falls to the lowest unoccupied cell in that column.</p>"
        "<h4>Legal Actions Mask</h4>"
        "<p>The <code>observation['action_mask']</code> is a binary vector of length 7. "
        "A column is legal (mask=1) if it's not full. Taking an illegal action "
        "(dropping into a full column) ends the game with -1 reward.</p>"
        "<h4>Rewards</h4>"
        "<table>"
        "<tr><th>Winner</th><th>Loser</th><th>Draw</th></tr>"
        "<tr><td>+1</td><td>-1</td><td>0</td></tr>"
        "</table>"
        "<p>Rewards are given at game end. Draw occurs when board is full with no winner.</p>"
        "<h4>Usage (AEC)</h4>"
        "<pre><code>from pettingzoo.classic import connect_four_v3\n\n"
        "env = connect_four_v3.env(render_mode='human')\n"
        "env.reset(seed=42)\n\n"
        "for agent in env.agent_iter():\n"
        "    observation, reward, termination, truncation, info = env.last()\n\n"
        "    if termination or truncation:\n"
        "        action = None\n"
        "    else:\n"
        "        mask = observation['action_mask']\n"
        "        action = env.action_space(agent).sample(mask)\n\n"
        "    env.step(action)\n"
        "env.close()</code></pre>"
        "<h4>Human Control Mode</h4>"
        "<p>In the GUI, click on a column to drop your disc. The game alternates between "
        "player_0 (Red) and player_1 (Yellow). Invalid moves are rejected.</p>"
        "<h4>Version History</h4>"
        "<ul>"
        "<li><strong>v3:</strong> Fixed observation shape and action mask bugs (1.8.0)</li>"
        "<li><strong>v2:</strong> Bumped to using observation['action_mask'] (1.5.0)</li>"
        "<li><strong>v1:</strong> Bumped version for all envs (1.4.0)</li>"
        "<li><strong>v0:</strong> Initial release</li>"
        "</ul>"
        "<p>Docs: <a href='https://pettingzoo.farama.org/environments/classic/connect_four/'>PettingZoo Connect Four</a></p>"
    )


# For backward compatibility
CONNECT_FOUR_HTML = get_connect_four_html()

__all__ = ["CONNECT_FOUR_HTML", "get_connect_four_html"]
