"""Documentation for PettingZoo Chess."""
from __future__ import annotations


def get_chess_html(env_id: str = "chess_v6") -> str:
    """Generate Chess HTML documentation."""
    return (
        "<h3>PettingZoo: Chess (chess_v6)</h3>"
        "<p>Chess is one of the oldest studied games in AI. This implementation uses "
        "the AlphaZero observation and action spaces with minor modifications. "
        "Two players compete on an 8×8 board to checkmate the opponent's king.</p>"
        "<h4>Environment Details</h4>"
        "<ul>"
        "<li><strong>Import:</strong> <code>from pettingzoo.classic import chess_v6</code></li>"
        "<li><strong>API Type:</strong> AEC (turn-based)</li>"
        "<li><strong>Parallel API:</strong> Yes</li>"
        "<li><strong>Agents:</strong> ['player_0', 'player_1']</li>"
        "<li><strong>Action Shape:</strong> Discrete(4672)</li>"
        "<li><strong>Observation Shape:</strong> (8, 8, 111)</li>"
        "<li><strong>Observation Values:</strong> [0, 1]</li>"
        "</ul>"
        "<h4>Observation Space</h4>"
        "<p>8×8×111 tensor representing the board state (AlphaZero style):</p>"
        "<ul>"
        "<li><strong>Channels 0-3:</strong> Castling rights (white/black queenside/kingside)</li>"
        "<li><strong>Channel 4:</strong> Current player indicator (is black's turn)</li>"
        "<li><strong>Channel 5:</strong> 50-move rule clock (normalized)</li>"
        "<li><strong>Channel 6:</strong> All ones (board edge detection)</li>"
        "<li><strong>Channels 7-18:</strong> Piece positions (6 white + 6 black piece types)</li>"
        "<li><strong>Channel 19:</strong> 2-fold repetition marker</li>"
        "<li><strong>Channels 20-111:</strong> Previous 7 board states (8 total history frames)</li>"
        "</ul>"
        "<h4>Action Space</h4>"
        "<p>Flattened 8×8×73 = 4672 discrete actions (AlphaZero encoding):</p>"
        "<ul>"
        "<li><strong>Planes 0-55:</strong> Queen-like moves (7 directions × 7 distances + 1)</li>"
        "<li><strong>Planes 56-63:</strong> Knight moves (8 L-shaped moves)</li>"
        "<li><strong>Planes 64-72:</strong> Underpromotions (3 piece types × 3 directions)</li>"
        "</ul>"
        "<p>Decode action formula: <code>(a // (8*73), (a // 73) % 8, a % (8*73) % 73)</code></p>"
        "<h4>Legal Actions Mask</h4>"
        "<p>The <code>observation['action_mask']</code> is a binary vector of length 4672 indicating legal moves. "
        "Taking an illegal move ends the game immediately with -1 reward.</p>"
        "<h4>Game End Conditions</h4>"
        "<ul>"
        "<li><strong>Checkmate:</strong> Winner gets +1, loser gets -1</li>"
        "<li><strong>Stalemate:</strong> Both players get 0 (draw)</li>"
        "<li><strong>50-move rule:</strong> Draw if 50 moves without pawn move or capture</li>"
        "<li><strong>3-fold repetition:</strong> Draw if same position occurs 3 times</li>"
        "<li><strong>Insufficient material:</strong> Draw (e.g., K vs K, K+B vs K)</li>"
        "</ul>"
        "<h4>Rewards</h4>"
        "<table>"
        "<tr><th>Winner</th><th>Loser</th><th>Draw</th></tr>"
        "<tr><td>+1</td><td>-1</td><td>0</td></tr>"
        "</table>"
        "<h4>Usage (AEC)</h4>"
        "<pre><code>from pettingzoo.classic import chess_v6\n\n"
        "env = chess_v6.env(render_mode='human')\n"
        "env.reset(seed=42)\n\n"
        "for agent in env.agent_iter():\n"
        "    observation, reward, termination, truncation, info = env.last()\n\n"
        "    if termination or truncation:\n"
        "        action = None\n"
        "    else:\n"
        "        mask = observation['action_mask']\n"
        "        action = env.action_space(agent).sample(mask)\n\n"
        "    env.step(action)\n"
        "env.close()</code></pre>"
        "<h4>Human Control Mode</h4>"
        "<p>In the GUI, click a piece to select it, then click the destination square. "
        "Valid moves are highlighted. The game alternates between player_0 (White) "
        "and player_1 (Black). Pawn promotion automatically promotes to queen.</p>"
        "<h4>Version History</h4>"
        "<ul>"
        "<li><strong>v6:</strong> Fixed wrong player starting, check for insufficient material/50-turn rule/repetition (1.23.2)</li>"
        "<li><strong>v5:</strong> Changed python-chess to version 1.7 (1.13.1)</li>"
        "<li><strong>v4:</strong> AlphaZero style frame stacking (1.11.0)</li>"
        "<li><strong>v3:</strong> Added legal action mask to observations (1.5.0)</li>"
        "</ul>"
        "<p>Docs: <a href='https://pettingzoo.farama.org/environments/classic/chess/'>PettingZoo Chess</a></p>"
    )


# For backward compatibility
CHESS_HTML = get_chess_html()

__all__ = ["CHESS_HTML", "get_chess_html"]
