"""Canonical help text (HTML) for environments displayed in the Game Info panel."""

from __future__ import annotations

from typing import Dict

from gym_gui.core.enums import GameId
from gym_gui.game_docs.Gymnasium.ToyText import (
    TAXI_HTML,
    FROZEN_HTML,
    FROZEN_V2_HTML,
    CLIFF_HTML,
    BLACKJACK_HTML,
)

from gym_gui.game_docs.Gymnasium.Box2D import (
    LUNAR_LANDER_HTML,
    CAR_RACING_HTML,
    BIPEDAL_WALKER_HTML,
)
from gym_gui.game_docs.Gymnasium.MuJuCo import (
    ANT_HTML,
    HALF_CHEETAH_HTML,
    HOPPER_HTML,
    HUMANOID_HTML,
    HUMANOID_STANDUP_HTML,
    INVERTED_DOUBLE_PENDULUM_HTML,
    INVERTED_PENDULUM_HTML,
    PUSHER_HTML,
    REACHER_HTML,
    SWIMMER_HTML,
    WALKER2D_HTML,
)

from gym_gui.game_docs.MiniGrid import (
    MINIGRID_EMPTY_HTML,
    MINIGRID_DOORKEY_HTML,
    MINIGRID_LAVAGAP_HTML,
    MINIGRID_DYNAMIC_OBSTACLES_HTML,
    MINIGRID_BLOCKED_UNLOCK_PICKUP_HTML,
    MINIGRID_MULTIROOM_HTML,
    MINIGRID_OBSTRUCTED_MAZE_HTML,
)
from gym_gui.game_docs.ALE import (
    ADVENTURE_HTML,
)
from gym_gui.game_docs.PettingZoo import (
    CHESS_HTML,
    CONNECT_FOUR_HTML,
    GO_HTML,
    TICTACTOE_HTML,
)
from gym_gui.game_docs.MiniHack import (
    MINIHACK_ROOM_HTML,
    MINIHACK_CORRIDOR_HTML,
    MINIHACK_MAZEWALK_HTML,
    MINIHACK_RIVER_HTML,
    MINIHACK_SKILLS_SIMPLE_HTML,
    MINIHACK_SKILLS_LAVA_HTML,
    MINIHACK_SKILLS_WOD_HTML,
    MINIHACK_EXPLORE_MAZE_HTML,
    MINIHACK_HIDENSEEK_HTML,
    MINIHACK_MEMENTO_HTML,
)
from gym_gui.game_docs.crafter import (
    CRAFTER_REWARD_HTML,
    CRAFTER_NO_REWARD_HTML,
)
from gym_gui.game_docs.NetHack import (
    NETHACK_FULL_HTML,
)
from gym_gui.game_docs.Procgen import (
    PROCGEN_BIGFISH_HTML,
    PROCGEN_BOSSFIGHT_HTML,
    PROCGEN_CAVEFLYER_HTML,
    PROCGEN_CHASER_HTML,
    PROCGEN_CLIMBER_HTML,
    PROCGEN_COINRUN_HTML,
    PROCGEN_DODGEBALL_HTML,
    PROCGEN_FRUITBOT_HTML,
    PROCGEN_HEIST_HTML,
    PROCGEN_JUMPER_HTML,
    PROCGEN_LEAPER_HTML,
    PROCGEN_MAZE_HTML,
    PROCGEN_MINER_HTML,
    PROCGEN_NINJA_HTML,
    PROCGEN_PLUNDER_HTML,
    PROCGEN_STARPILOT_HTML,
)
from gym_gui.game_docs.Jumanji import (
    GAME2048_HTML,
    MINESWEEPER_HTML,
    RUBIKS_CUBE_HTML,
    SLIDING_PUZZLE_HTML,
    SUDOKU_HTML,
    GRAPH_COLORING_HTML,
)
from gym_gui.game_docs.OpenSpiel import (
    CHECKERS_HTML,
)


GAME_INFO: Dict[GameId, str] = {
    GameId.TAXI: TAXI_HTML,
    GameId.FROZEN_LAKE: FROZEN_HTML,
    GameId.FROZEN_LAKE_V2: FROZEN_V2_HTML,
    GameId.CLIFF_WALKING: CLIFF_HTML,
    GameId.BLACKJACK: BLACKJACK_HTML,
    GameId.LUNAR_LANDER: LUNAR_LANDER_HTML,
    GameId.CAR_RACING: CAR_RACING_HTML,
    GameId.BIPEDAL_WALKER: BIPEDAL_WALKER_HTML,
    GameId.ANT: ANT_HTML,
    GameId.HALF_CHEETAH: HALF_CHEETAH_HTML,
    GameId.HOPPER: HOPPER_HTML,
    GameId.HUMANOID: HUMANOID_HTML,
    GameId.HUMANOID_STANDUP: HUMANOID_STANDUP_HTML,
    GameId.INVERTED_DOUBLE_PENDULUM: INVERTED_DOUBLE_PENDULUM_HTML,
    GameId.INVERTED_PENDULUM: INVERTED_PENDULUM_HTML,
    GameId.PUSHER: PUSHER_HTML,
    GameId.REACHER: REACHER_HTML,
    GameId.SWIMMER: SWIMMER_HTML,
    GameId.WALKER2D: WALKER2D_HTML,
}


_MINIGRID_EMPTY_VARIANTS = (
    GameId.MINIGRID_EMPTY_5x5,
    GameId.MINIGRID_EMPTY_RANDOM_5x5,
    GameId.MINIGRID_EMPTY_6x6,
    GameId.MINIGRID_EMPTY_RANDOM_6x6,
    GameId.MINIGRID_EMPTY_8x8,
    GameId.MINIGRID_EMPTY_16x16,
)
GAME_INFO.update({gid: MINIGRID_EMPTY_HTML for gid in _MINIGRID_EMPTY_VARIANTS})


_MINIGRID_DOORKEY_VARIANTS = (
    GameId.MINIGRID_DOORKEY_5x5,
    GameId.MINIGRID_DOORKEY_6x6,
    GameId.MINIGRID_DOORKEY_8x8,
    GameId.MINIGRID_DOORKEY_16x16,
)
GAME_INFO.update({gid: MINIGRID_DOORKEY_HTML for gid in _MINIGRID_DOORKEY_VARIANTS})


_MINIGRID_LAVAGAP_VARIANTS = (
    GameId.MINIGRID_LAVAGAP_S5,
    GameId.MINIGRID_LAVAGAP_S6,
    GameId.MINIGRID_LAVAGAP_S7,
)
GAME_INFO.update({gid: MINIGRID_LAVAGAP_HTML for gid in _MINIGRID_LAVAGAP_VARIANTS})


_MINIGRID_DYNAMIC_OBSTACLES_VARIANTS = (
    GameId.MINIGRID_DYNAMIC_OBSTACLES_5X5,
    GameId.MINIGRID_DYNAMIC_OBSTACLES_RANDOM_5X5,
    GameId.MINIGRID_DYNAMIC_OBSTACLES_6X6,
    GameId.MINIGRID_DYNAMIC_OBSTACLES_RANDOM_6X6,
    GameId.MINIGRID_DYNAMIC_OBSTACLES_8X8,
    GameId.MINIGRID_DYNAMIC_OBSTACLES_16X16,
)
GAME_INFO.update({gid: MINIGRID_DYNAMIC_OBSTACLES_HTML for gid in _MINIGRID_DYNAMIC_OBSTACLES_VARIANTS})


GAME_INFO[GameId.MINIGRID_BLOCKED_UNLOCK_PICKUP] = MINIGRID_BLOCKED_UNLOCK_PICKUP_HTML


_MINIGRID_MULTIROOM_VARIANTS = (
    GameId.MINIGRID_MULTIROOM_N2_S4,
    GameId.MINIGRID_MULTIROOM_N4_S5,
    GameId.MINIGRID_MULTIROOM_N6,
)
GAME_INFO.update({gid: MINIGRID_MULTIROOM_HTML for gid in _MINIGRID_MULTIROOM_VARIANTS})


GAME_INFO[GameId.MINIGRID_OBSTRUCTED_MAZE_1DLHB] = MINIGRID_OBSTRUCTED_MAZE_HTML
GAME_INFO[GameId.MINIGRID_OBSTRUCTED_MAZE_FULL] = MINIGRID_OBSTRUCTED_MAZE_HTML

# ALE mappings
GAME_INFO[GameId.ADVENTURE_V4] = ADVENTURE_HTML
GAME_INFO[GameId.ALE_ADVENTURE_V5] = ADVENTURE_HTML

# PettingZoo mappings
GAME_INFO[GameId.CHESS] = CHESS_HTML
GAME_INFO[GameId.CONNECT_FOUR] = CONNECT_FOUR_HTML
GAME_INFO[GameId.GO] = GO_HTML
GAME_INFO[GameId.TIC_TAC_TOE] = TICTACTOE_HTML

# MiniHack Navigation mappings
_MINIHACK_ROOM_VARIANTS = (
    GameId.MINIHACK_ROOM_5X5,
    GameId.MINIHACK_ROOM_15X15,
)
GAME_INFO.update({gid: MINIHACK_ROOM_HTML for gid in _MINIHACK_ROOM_VARIANTS})

_MINIHACK_CORRIDOR_VARIANTS = (
    GameId.MINIHACK_CORRIDOR_R2,
    GameId.MINIHACK_CORRIDOR_R3,
    GameId.MINIHACK_CORRIDOR_R5,
)
GAME_INFO.update({gid: MINIHACK_CORRIDOR_HTML for gid in _MINIHACK_CORRIDOR_VARIANTS})

_MINIHACK_MAZEWALK_VARIANTS = (
    GameId.MINIHACK_MAZEWALK_9X9,
    GameId.MINIHACK_MAZEWALK_15X15,
    GameId.MINIHACK_MAZEWALK_45X19,
)
GAME_INFO.update({gid: MINIHACK_MAZEWALK_HTML for gid in _MINIHACK_MAZEWALK_VARIANTS})

_MINIHACK_RIVER_VARIANTS = (
    GameId.MINIHACK_RIVER,
    GameId.MINIHACK_RIVER_NARROW,
)
GAME_INFO.update({gid: MINIHACK_RIVER_HTML for gid in _MINIHACK_RIVER_VARIANTS})

# MiniHack Skills mappings
_MINIHACK_SKILLS_SIMPLE_VARIANTS = (
    GameId.MINIHACK_EAT,
    GameId.MINIHACK_WEAR,
    GameId.MINIHACK_WIELD,
    GameId.MINIHACK_ZAP,
    GameId.MINIHACK_READ,
    GameId.MINIHACK_QUAFF,
    GameId.MINIHACK_PUTON,
)
GAME_INFO.update({gid: MINIHACK_SKILLS_SIMPLE_HTML for gid in _MINIHACK_SKILLS_SIMPLE_VARIANTS})

GAME_INFO[GameId.MINIHACK_LAVACROSS] = MINIHACK_SKILLS_LAVA_HTML

_MINIHACK_WOD_VARIANTS = (
    GameId.MINIHACK_WOD_EASY,
    GameId.MINIHACK_WOD_MEDIUM,
    GameId.MINIHACK_WOD_HARD,
)
GAME_INFO.update({gid: MINIHACK_SKILLS_WOD_HTML for gid in _MINIHACK_WOD_VARIANTS})

# MiniHack Exploration mappings
_MINIHACK_EXPLOREMAZE_VARIANTS = (
    GameId.MINIHACK_EXPLOREMAZE_EASY,
    GameId.MINIHACK_EXPLOREMAZE_HARD,
)
GAME_INFO.update({gid: MINIHACK_EXPLORE_MAZE_HTML for gid in _MINIHACK_EXPLOREMAZE_VARIANTS})

GAME_INFO[GameId.MINIHACK_HIDENSEEK] = MINIHACK_HIDENSEEK_HTML

_MINIHACK_MEMENTO_VARIANTS = (
    GameId.MINIHACK_MEMENTO_F2,
    GameId.MINIHACK_MEMENTO_F4,
)
GAME_INFO.update({gid: MINIHACK_MEMENTO_HTML for gid in _MINIHACK_MEMENTO_VARIANTS})

# Crafter mappings
GAME_INFO[GameId.CRAFTER_REWARD] = CRAFTER_REWARD_HTML
GAME_INFO[GameId.CRAFTER_NO_REWARD] = CRAFTER_NO_REWARD_HTML

# NetHack (full game) mappings
_NETHACK_VARIANTS = (
    GameId.NETHACK_FULL,
    GameId.NETHACK_SCORE,
    GameId.NETHACK_STAIRCASE,
    GameId.NETHACK_STAIRCASE_PET,
    GameId.NETHACK_ORACLE,
    GameId.NETHACK_GOLD,
    GameId.NETHACK_EAT,
    GameId.NETHACK_SCOUT,
)
GAME_INFO.update({gid: NETHACK_FULL_HTML for gid in _NETHACK_VARIANTS})

# Procgen mappings (16 environments)
GAME_INFO[GameId.PROCGEN_BIGFISH] = PROCGEN_BIGFISH_HTML
GAME_INFO[GameId.PROCGEN_BOSSFIGHT] = PROCGEN_BOSSFIGHT_HTML
GAME_INFO[GameId.PROCGEN_CAVEFLYER] = PROCGEN_CAVEFLYER_HTML
GAME_INFO[GameId.PROCGEN_CHASER] = PROCGEN_CHASER_HTML
GAME_INFO[GameId.PROCGEN_CLIMBER] = PROCGEN_CLIMBER_HTML
GAME_INFO[GameId.PROCGEN_COINRUN] = PROCGEN_COINRUN_HTML
GAME_INFO[GameId.PROCGEN_DODGEBALL] = PROCGEN_DODGEBALL_HTML
GAME_INFO[GameId.PROCGEN_FRUITBOT] = PROCGEN_FRUITBOT_HTML
GAME_INFO[GameId.PROCGEN_HEIST] = PROCGEN_HEIST_HTML
GAME_INFO[GameId.PROCGEN_JUMPER] = PROCGEN_JUMPER_HTML
GAME_INFO[GameId.PROCGEN_LEAPER] = PROCGEN_LEAPER_HTML
GAME_INFO[GameId.PROCGEN_MAZE] = PROCGEN_MAZE_HTML
GAME_INFO[GameId.PROCGEN_MINER] = PROCGEN_MINER_HTML
GAME_INFO[GameId.PROCGEN_NINJA] = PROCGEN_NINJA_HTML
GAME_INFO[GameId.PROCGEN_PLUNDER] = PROCGEN_PLUNDER_HTML
GAME_INFO[GameId.PROCGEN_STARPILOT] = PROCGEN_STARPILOT_HTML

# Jumanji mappings (JAX-based logic puzzle environments)
GAME_INFO[GameId.JUMANJI_GAME2048] = GAME2048_HTML
GAME_INFO[GameId.JUMANJI_MINESWEEPER] = MINESWEEPER_HTML
GAME_INFO[GameId.JUMANJI_RUBIKS_CUBE] = RUBIKS_CUBE_HTML
GAME_INFO[GameId.JUMANJI_SLIDING_PUZZLE] = SLIDING_PUZZLE_HTML
GAME_INFO[GameId.JUMANJI_SUDOKU] = SUDOKU_HTML
GAME_INFO[GameId.JUMANJI_GRAPH_COLORING] = GRAPH_COLORING_HTML

# OpenSpiel mappings (board games via Shimmy wrapper)
GAME_INFO[GameId.OPEN_SPIEL_CHECKERS] = CHECKERS_HTML


__all__ = ["GAME_INFO"]
