"""Documentation for ALE Pong (2-Player)."""
from __future__ import annotations

PONG_HTML = (
    "<h3>ALE: Pong (2-Player)</h3>"
    "<p>Classic two-player Pong - the original competitive video game. Each player "
    "controls a paddle to hit the ball past their opponent. First to 21 points wins.</p>"
    "<h4>Make (Two-Player)</h4>"
    "<pre><code>from pettingzoo.atari import pong_v3\n"
    "env = pong_v3.parallel_env()</code></pre>"
    "<h4>Players</h4>"
    "<ul>"
    "<li><strong>Number of agents:</strong> 2</li>"
    "<li><strong>Agent IDs:</strong> <code>first_0</code>, <code>second_0</code></li>"
    "</ul>"
    "<h4>Action Space</h4>"
    "<p><code>Discrete(6)</code></p>"
    "<ul>"
    "<li>0: No operation</li>"
    "<li>1: Fire (serve)</li>"
    "<li>2: Move right</li>"
    "<li>3: Move left</li>"
    "<li>4: Move right + fire</li>"
    "<li>5: Move left + fire</li>"
    "</ul>"
    "<h4>Observation Space</h4>"
    "<p><code>Box(0, 255, (210, 160, 3), uint8)</code> - RGB image</p>"
    "<h4>Game Mechanics</h4>"
    "<ul>"
    "<li>Control paddle to deflect ball toward opponent</li>"
    "<li>Ball speed increases throughout rally</li>"
    "<li>Score when ball passes opponent's paddle</li>"
    "<li>First to 21 points wins the game</li>"
    "</ul>"
    "<h4>Rewards (Zero-Sum)</h4>"
    "<ul>"
    "<li>Score a point: <strong>+1</strong> reward</li>"
    "<li>Opponent scores: <strong>-1</strong> reward</li>"
    "</ul>"
    "<h4>Game Type</h4>"
    "<p><strong>Competitive</strong> - Head-to-head paddle game.</p>"
    "<p>Docs: <a href='https://pettingzoo.farama.org/environments/atari/pong/'>"
    "PettingZoo: Pong</a></p>"
)

__all__ = ["PONG_HTML"]
