"""Documentation for ALE Entombed: Competitive (2-Player)."""
from __future__ import annotations

ENTOMBED_COMPETITIVE_HTML = (
    "<h3>ALE: Entombed Competitive (2-Player)</h3>"
    "<p>A competitive survival game where two players race to outlast each other "
    "in a constantly generating maze. Navigate through a partially visible maze "
    "while avoiding zombies and potential dead-ends.</p>"
    "<h4>Make (Two-Player)</h4>"
    "<pre><code>from pettingzoo.atari import entombed_competitive_v3\n"
    "env = entombed_competitive_v3.parallel_env()</code></pre>"
    "<h4>Players</h4>"
    "<ul>"
    "<li><strong>Number of agents:</strong> 2</li>"
    "<li><strong>Agent IDs:</strong> <code>first_0</code>, <code>second_0</code></li>"
    "</ul>"
    "<h4>Action Space</h4>"
    "<p><code>Discrete(18)</code> - Full Atari action set including:</p>"
    "<ul>"
    "<li>Movement in 8 directions</li>"
    "<li>Fire actions in various directions</li>"
    "<li>No operation</li>"
    "</ul>"
    "<h4>Observation Space</h4>"
    "<p><code>Box(0, 255, (210, 160, 3), uint8)</code> - RGB image</p>"
    "<h4>Game Mechanics</h4>"
    "<ul>"
    "<li>Navigate a dynamically-generated maze with limited visibility</li>"
    "<li>Avoid zombies throughout the maze</li>"
    "<li>Dead-ends may require rare power-ups to escape</li>"
    "<li>Survive longer than your opponent to win</li>"
    "</ul>"
    "<h4>Rewards (Zero-Sum)</h4>"
    "<ul>"
    "<li>Opponent dies: <strong>+1</strong> reward</li>"
    "<li>You die: <strong>-1</strong> reward</li>"
    "</ul>"
    "<h4>Game Type</h4>"
    "<p><strong>Competitive</strong> - Last player surviving wins.</p>"
    "<p>Docs: <a href='https://pettingzoo.farama.org/environments/atari/entombed_competitive/'>"
    "PettingZoo: Entombed Competitive</a></p>"
)

__all__ = ["ENTOMBED_COMPETITIVE_HTML"]
