"""Documentation for ALE Space War (2-Player)."""
from __future__ import annotations

SPACE_WAR_HTML = (
    "<h3>ALE: Space War (2-Player)</h3>"
    "<p>A competitive space combat game where prediction and positioning are key. "
    "Features an advanced physics system where acceleration and momentum need to be "
    "taken into account.</p>"
    "<h4>Make (Two-Player)</h4>"
    "<pre><code>from pettingzoo.atari import space_war_v2\n"
    "env = space_war_v2.parallel_env()</code></pre>"
    "<h4>Players</h4>"
    "<ul>"
    "<li><strong>Number of agents:</strong> 2</li>"
    "<li><strong>Agent IDs:</strong> <code>first_0</code>, <code>second_0</code></li>"
    "</ul>"
    "<h4>Action Space</h4>"
    "<p><code>Discrete(18)</code> - Full Atari action set including:</p>"
    "<ul>"
    "<li>Movement in 8 directions</li>"
    "<li>Fire actions in various directions</li>"
    "<li>Combined fire + movement actions</li>"
    "<li>No operation</li>"
    "</ul>"
    "<h4>Observation Space</h4>"
    "<p><code>Box(0, 255, (250, 160, 3), uint8)</code> - RGB image</p>"
    "<h4>Game Mechanics</h4>"
    "<ul>"
    "<li>Navigate with momentum-based physics</li>"
    "<li>Account for acceleration and inertia when moving</li>"
    "<li>Position strategically to land shots</li>"
    "<li>Predict opponent movement to score hits</li>"
    "</ul>"
    "<h4>Rewards (Zero-Sum)</h4>"
    "<ul>"
    "<li>Hit opponent: <strong>+1</strong> reward</li>"
    "<li>Get hit: <strong>-1</strong> reward</li>"
    "</ul>"
    "<h4>Game Type</h4>"
    "<p><strong>Competitive</strong> - Outmaneuver and outshoot your opponent.</p>"
    "<p>Docs: <a href='https://pettingzoo.farama.org/environments/atari/space_war/'>"
    "PettingZoo: Space War</a></p>"
)

__all__ = ["SPACE_WAR_HTML"]
