"""Documentation for PettingZoo Butterfly Pistonball environment."""
from __future__ import annotations


def get_pistonball_html(env_id: str = "pistonball_v6") -> str:
    """Generate Pistonball environment HTML documentation."""
    return (
        "<h3>PettingZoo Butterfly: Pistonball (pistonball_v6)</h3>"
        "<p>A physics-based cooperative game where vertically-moving pistons must coordinate "
        "to move a ball to the left wall. Optimal policy requires highly coordinated behavior.</p>"
        "<h4>Environment Details</h4>"
        "<ul>"
        "<li><strong>Import:</strong> <code>from pettingzoo.butterfly import pistonball_v6</code></li>"
        "<li><strong>Actions:</strong> Discrete or Continuous</li>"
        "<li><strong>Parallel API:</strong> Yes</li>"
        "<li><strong>Manual Control:</strong> Yes (A/D to select piston, W/S to move)</li>"
        "<li><strong>Agents:</strong> ['piston_0', ..., 'piston_19'] (default 20)</li>"
        "<li><strong>Action Shape:</strong> (1,) discrete or [-1, 1] continuous</li>"
        "<li><strong>Observation Shape:</strong> (457, 120, 3) - local view</li>"
        "<li><strong>State Shape:</strong> (560, 880, 3) - full view</li>"
        "</ul>"
        "<h4>Observations</h4>"
        "<p>Each piston sees itself, immediate neighbors (or walls), and space above "
        "(which may show the ball).</p>"
        "<h4>Actions</h4>"
        "<ul>"
        "<li><strong>Discrete:</strong> 0=down 4px, 1=stay, 2=up 4px</li>"
        "<li><strong>Continuous:</strong> [-1, 1] scaled by 4px</li>"
        "</ul>"
        "<h4>Rewards</h4>"
        "<p>Shared reward based on:</p>"
        "<ul>"
        "<li>Ball movement toward left wall (% of initial distance)</li>"
        "<li>Time penalty (default: -0.1 per step)</li>"
        "</ul>"
        "<h4>Key Arguments</h4>"
        "<pre><code>pistonball_v6.env(\n"
        "    n_pistons=20,\n"
        "    time_penalty=-0.1,\n"
        "    continuous=True,\n"
        "    random_drop=True,      # Ball spawns at random x\n"
        "    random_rotate=True,    # Ball has random initial spin\n"
        "    ball_mass=0.75,\n"
        "    ball_friction=0.3,\n"
        "    ball_elasticity=1.5,\n"
        "    max_cycles=125\n"
        ")</code></pre>"
        "<h4>Usage</h4>"
        "<pre><code>from pettingzoo.butterfly import pistonball_v6\n\n"
        "env = pistonball_v6.env(render_mode='human')\n"
        "env.reset(seed=42)\n\n"
        "for agent in env.agent_iter():\n"
        "    obs, reward, term, trunc, info = env.last()\n"
        "    action = None if term or trunc else env.action_space(agent).sample()\n"
        "    env.step(action)\n"
        "env.close()</code></pre>"
        "<h4>Parallel Usage</h4>"
        "<pre><code>env = pistonball_v6.parallel_env(render_mode='human')\n"
        "observations, infos = env.reset()\n\n"
        "while env.agents:\n"
        "    actions = {agent: env.action_space(agent).sample() for agent in env.agents}\n"
        "    observations, rewards, terminations, truncations, infos = env.step(actions)\n"
        "env.close()</code></pre>"
    )


PISTONBALL_HTML = get_pistonball_html()

__all__ = ["PISTONBALL_HTML", "get_pistonball_html"]
