"""Documentation for ALE Mario Bros (2-Player)."""
from __future__ import annotations

MARIO_BROS_HTML = (
    "<h3>ALE: Mario Bros (2-Player)</h3>"
    "<p>The original Mario Bros arcade game. Mario and Luigi cooperate to clear "
    "enemies from the sewers by hitting platforms from below, then kicking them off.</p>"
    "<h4>Make (Two-Player)</h4>"
    "<pre><code>from pettingzoo.atari import mario_bros_v3\n"
    "env = mario_bros_v3.parallel_env()</code></pre>"
    "<h4>Players</h4>"
    "<ul>"
    "<li><strong>Number of agents:</strong> 2</li>"
    "<li><strong>Agent IDs:</strong> <code>first_0</code> (Mario), <code>second_0</code> (Luigi)</li>"
    "</ul>"
    "<h4>Action Space</h4>"
    "<p><code>Discrete(18)</code> - Full Atari action set including:</p>"
    "<ul>"
    "<li>Movement in all directions</li>"
    "<li>Jump (fire button)</li>"
    "<li>Combined movement + jump</li>"
    "</ul>"
    "<h4>Observation Space</h4>"
    "<p><code>Box(0, 255, (210, 160, 3), uint8)</code> - RGB image</p>"
    "<h4>Game Mechanics</h4>"
    "<ul>"
    "<li>Hit floor from below to flip enemies</li>"
    "<li>Kick flipped enemies off the platform</li>"
    "<li>Collect coins and bonus items for extra points</li>"
    "<li>Avoid active pests and fireballs</li>"
    "</ul>"
    "<h4>Rewards</h4>"
    "<ul>"
    "<li>Kick pest off floor: <strong>+800</strong> points</li>"
    "<li>Collect coin/wafer: <strong>+800</strong> points</li>"
    "<li>Extra life at 20,000 points</li>"
    "</ul>"
    "<h4>Special Rules</h4>"
    "<ul>"
    "<li>Players share lives</li>"
    "<li>Can help or hinder each other</li>"
    "<li>Eliminated player's partner continues alone</li>"
    "</ul>"
    "<h4>Game Type</h4>"
    "<p><strong>Mixed-Sum</strong> - Cooperative or competitive gameplay.</p>"
    "<p>Docs: <a href='https://pettingzoo.farama.org/environments/atari/mario_bros/'>"
    "PettingZoo: Mario Bros</a></p>"
)

__all__ = ["MARIO_BROS_HTML"]
