"""Documentation for ALE Surround (2-Player)."""
from __future__ import annotations

SURROUND_HTML = (
    "<h3>ALE: Surround (2-Player)</h3>"
    "<p>Tron-like light cycle game where players leave trails behind them. Avoid "
    "crashing into walls, trails, or each other. Last player standing wins.</p>"
    "<h4>Make (Two-Player)</h4>"
    "<pre><code>from pettingzoo.atari import surround_v2\n"
    "env = surround_v2.parallel_env()</code></pre>"
    "<h4>Players</h4>"
    "<ul>"
    "<li><strong>Number of agents:</strong> 2</li>"
    "<li><strong>Agent IDs:</strong> <code>first_0</code>, <code>second_0</code></li>"
    "</ul>"
    "<h4>Action Space</h4>"
    "<p><code>Discrete(5)</code></p>"
    "<ul>"
    "<li>0: No operation</li>"
    "<li>1: Move up</li>"
    "<li>2: Move right</li>"
    "<li>3: Move left</li>"
    "<li>4: Move down</li>"
    "</ul>"
    "<h4>Observation Space</h4>"
    "<p><code>Box(0, 255, (210, 160, 3), uint8)</code> - RGB image</p>"
    "<h4>Game Mechanics</h4>"
    "<ul>"
    "<li>Players constantly move, leaving trails</li>"
    "<li>Cannot stop or reverse direction</li>"
    "<li>Crashing into any trail or wall eliminates you</li>"
    "<li>Trap your opponent while avoiding being trapped</li>"
    "</ul>"
    "<h4>Rewards (Zero-Sum)</h4>"
    "<ul>"
    "<li>Opponent crashes: <strong>+1</strong> reward</li>"
    "<li>You crash: <strong>-1</strong> reward</li>"
    "</ul>"
    "<h4>Game Type</h4>"
    "<p><strong>Competitive</strong> - Survival strategy game.</p>"
    "<p>Docs: <a href='https://pettingzoo.farama.org/environments/atari/surround/'>"
    "PettingZoo: Surround</a></p>"
)

__all__ = ["SURROUND_HTML"]
