"""Documentation for ALE Video Checkers (2-Player)."""
from __future__ import annotations

VIDEO_CHECKERS_HTML = (
    "<h3>ALE: Video Checkers (2-Player)</h3>"
    "<p>Classic checkers/draughts board game. Capture all of your opponent's pieces "
    "by jumping over them. Features king pieces that can move backwards.</p>"
    "<h4>Make (Two-Player)</h4>"
    "<pre><code>from pettingzoo.atari import video_checkers_v4\n"
    "env = video_checkers_v4.parallel_env()</code></pre>"
    "<h4>Players</h4>"
    "<ul>"
    "<li><strong>Number of agents:</strong> 2</li>"
    "<li><strong>Agent IDs:</strong> <code>first_0</code>, <code>second_0</code></li>"
    "</ul>"
    "<h4>Action Space</h4>"
    "<p><code>Discrete(5)</code></p>"
    "<ul>"
    "<li>0: Fire (select/confirm piece)</li>"
    "<li>1: Move up</li>"
    "<li>2: Move right</li>"
    "<li>3: Move left</li>"
    "<li>4: Move down</li>"
    "</ul>"
    "<h4>Observation Space</h4>"
    "<p><code>Box(0, 255, (210, 160, 3), uint8)</code> - RGB image</p>"
    "<h4>Game Mechanics</h4>"
    "<ul>"
    "<li>Select piece by hovering and pressing fire</li>"
    "<li>Move cursor to destination and press fire</li>"
    "<li>Buttons must be held for multiple frames</li>"
    "<li>Capture by jumping over opponent's pieces</li>"
    "<li>Reach opposite end to become a king</li>"
    "</ul>"
    "<h4>Rewards</h4>"
    "<ul>"
    "<li>Win game: <strong>+1</strong> reward</li>"
    "<li>Lose game: <strong>-1</strong> reward</li>"
    "<li>Timeout penalty (10 seconds): <strong>-1</strong> reward</li>"
    "</ul>"
    "<h4>Special Rules</h4>"
    "<p>Not purely zero-sum due to timeout mechanic - both players can lose points.</p>"
    "<h4>Game Type</h4>"
    "<p><strong>Competitive</strong> - Turn-based strategy.</p>"
    "<p>Docs: <a href='https://pettingzoo.farama.org/environments/atari/video_checkers/'>"
    "PettingZoo: Video Checkers</a></p>"
)

__all__ = ["VIDEO_CHECKERS_HTML"]
