"""Documentation for ALE Warlords (4-Player)."""
from __future__ import annotations

WARLORDS_HTML = (
    "<h3>ALE: Warlords (4-Player)</h3>"
    "<p>Medieval castle defense for up to 4 players. Each player protects their "
    "castle wall using a shield while trying to break through opponents' defenses "
    "with a bouncing fireball.</p>"
    "<h4>Make (Four-Player)</h4>"
    "<pre><code>from pettingzoo.atari import warlords_v3\n"
    "env = warlords_v3.parallel_env()</code></pre>"
    "<h4>Players</h4>"
    "<ul>"
    "<li><strong>Number of agents:</strong> 4</li>"
    "<li><strong>Agent IDs:</strong> <code>first_0</code>, <code>second_0</code>, "
    "<code>third_0</code>, <code>fourth_0</code></li>"
    "</ul>"
    "<h4>Action Space</h4>"
    "<p><code>Discrete(6)</code></p>"
    "<ul>"
    "<li>0: No operation</li>"
    "<li>1: Fire (catch and hold ball)</li>"
    "<li>2: Move up</li>"
    "<li>3: Move down</li>"
    "<li>4: Move up + fire</li>"
    "<li>5: Move down + fire</li>"
    "</ul>"
    "<h4>Observation Space</h4>"
    "<p><code>Box(0, 255, (210, 160, 3), uint8)</code> - RGB image</p>"
    "<h4>Game Mechanics</h4>"
    "<ul>"
    "<li>Move shield to deflect fireball</li>"
    "<li>Catch the ball to aim your throw</li>"
    "<li>Destroy opponents' castle bricks</li>"
    "<li>Eliminate a player by destroying their corner</li>"
    "</ul>"
    "<h4>Rewards (Zero-Sum)</h4>"
    "<ul>"
    "<li>Destroy opponent's brick: <strong>+1</strong> reward</li>"
    "<li>Your brick destroyed: <strong>-1</strong> reward</li>"
    "<li>Eliminate opponent: bonus reward</li>"
    "</ul>"
    "<h4>Game Type</h4>"
    "<p><strong>Competitive</strong> - Free-for-all castle defense.</p>"
    "<p>Docs: <a href='https://pettingzoo.farama.org/environments/atari/warlords/'>"
    "PettingZoo: Warlords</a></p>"
)

__all__ = ["WARLORDS_HTML"]
