# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc
import grpc.experimental as grpc_experimental

from . import trainer_pb2 as trainer__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in trainer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrainerServiceStub(object):
    """RPC surface for the trainer daemon.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitRun = channel.unary_unary(
                '/gymgui.trainer.TrainerService/SubmitRun',
                request_serializer=trainer__pb2.SubmitRunRequest.SerializeToString,
                response_deserializer=trainer__pb2.SubmitRunResponse.FromString,
                _registered_method=True)
        self.CancelRun = channel.unary_unary(
                '/gymgui.trainer.TrainerService/CancelRun',
                request_serializer=trainer__pb2.CancelRunRequest.SerializeToString,
                response_deserializer=trainer__pb2.CancelRunResponse.FromString,
                _registered_method=True)
        self.ListRuns = channel.unary_unary(
                '/gymgui.trainer.TrainerService/ListRuns',
                request_serializer=trainer__pb2.ListRunsRequest.SerializeToString,
                response_deserializer=trainer__pb2.ListRunsResponse.FromString,
                _registered_method=True)
        self.WatchRuns = channel.unary_stream(
                '/gymgui.trainer.TrainerService/WatchRuns',
                request_serializer=trainer__pb2.WatchRunsRequest.SerializeToString,
                response_deserializer=trainer__pb2.RunRecord.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/gymgui.trainer.TrainerService/Heartbeat',
                request_serializer=trainer__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=trainer__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.GetHealth = channel.unary_unary(
                '/gymgui.trainer.TrainerService/GetHealth',
                request_serializer=trainer__pb2.HealthCheckRequest.SerializeToString,  # type: ignore[attr-defined]
                response_deserializer=trainer__pb2.HealthCheckResponse.FromString,  # type: ignore[attr-defined]
                _registered_method=True)


class TrainerServiceServicer(object):
    """RPC surface for the trainer daemon.
    """

    def SubmitRun(self, request, context):
        """Registers a new training run and returns the canonical digest.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRun(self, request, context):
        """Cancels an in-flight run. No-op if the run already finished.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRuns(self, request, context):
        """Returns a snapshot of runs filtered by status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchRuns(self, request, context):
        """Streams updates for active runs. Yields whenever a run changes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Worker heartbeat hook to keep the run marked as healthy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealth(self, request, context):
        """Lightweight daemon heartbeat so the GUI can report liveness.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitRun': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitRun,
                    request_deserializer=trainer__pb2.SubmitRunRequest.FromString,
                    response_serializer=trainer__pb2.SubmitRunResponse.SerializeToString,
            ),
            'CancelRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRun,
                    request_deserializer=trainer__pb2.CancelRunRequest.FromString,
                    response_serializer=trainer__pb2.CancelRunResponse.SerializeToString,
            ),
            'ListRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRuns,
                    request_deserializer=trainer__pb2.ListRunsRequest.FromString,
                    response_serializer=trainer__pb2.ListRunsResponse.SerializeToString,
            ),
            'WatchRuns': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchRuns,
                    request_deserializer=trainer__pb2.WatchRunsRequest.FromString,
                    response_serializer=trainer__pb2.RunRecord.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=trainer__pb2.HeartbeatRequest.FromString,
                    response_serializer=trainer__pb2.HeartbeatResponse.SerializeToString,
            ),
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=trainer__pb2.HealthCheckRequest.FromString,  # type: ignore[attr-defined]
                    response_serializer=trainer__pb2.HealthCheckResponse.SerializeToString,  # type: ignore[attr-defined]
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gymgui.trainer.TrainerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gymgui.trainer.TrainerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrainerService(object):
    """RPC surface for the trainer daemon.
    """

    @staticmethod
    def SubmitRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc_experimental.unary_unary(
            request,
            target,
            '/gymgui.trainer.TrainerService/SubmitRun',
            trainer__pb2.SubmitRunRequest.SerializeToString,
            trainer__pb2.SubmitRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc_experimental.unary_unary(
            request,
            target,
            '/gymgui.trainer.TrainerService/CancelRun',
            trainer__pb2.CancelRunRequest.SerializeToString,
            trainer__pb2.CancelRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc_experimental.unary_unary(
            request,
            target,
            '/gymgui.trainer.TrainerService/ListRuns',
            trainer__pb2.ListRunsRequest.SerializeToString,
            trainer__pb2.ListRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc_experimental.unary_stream(
            request,
            target,
            '/gymgui.trainer.TrainerService/WatchRuns',
            trainer__pb2.WatchRunsRequest.SerializeToString,
            trainer__pb2.RunRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc_experimental.unary_unary(
            request,
            target,
            '/gymgui.trainer.TrainerService/Heartbeat',
            trainer__pb2.HeartbeatRequest.SerializeToString,
            trainer__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
                return grpc_experimental.unary_unary(
            request,
            target,
            '/gymgui.trainer.TrainerService/GetHealth',
                        trainer__pb2.HealthCheckRequest.SerializeToString,  # type: ignore[attr-defined]
                        trainer__pb2.HealthCheckResponse.FromString,  # type: ignore[attr-defined]
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
