# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from gym_gui.services.trainer.proto import trainer_pb2 as gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in gym_gui/services/trainer/proto/trainer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrainerServiceStub(object):
    """RPC surface for the trainer daemon.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitRun = channel.unary_unary(
                '/gymgui.trainer.TrainerService/SubmitRun',
                request_serializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.SubmitRunRequest.SerializeToString,
                response_deserializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.SubmitRunResponse.FromString,
                _registered_method=True)
        self.CancelRun = channel.unary_unary(
                '/gymgui.trainer.TrainerService/CancelRun',
                request_serializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.CancelRunRequest.SerializeToString,
                response_deserializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.CancelRunResponse.FromString,
                _registered_method=True)
        self.ListRuns = channel.unary_unary(
                '/gymgui.trainer.TrainerService/ListRuns',
                request_serializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.ListRunsRequest.SerializeToString,
                response_deserializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.ListRunsResponse.FromString,
                _registered_method=True)
        self.WatchRuns = channel.unary_stream(
                '/gymgui.trainer.TrainerService/WatchRuns',
                request_serializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.WatchRunsRequest.SerializeToString,
                response_deserializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.RunRecord.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/gymgui.trainer.TrainerService/Heartbeat',
                request_serializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.RegisterWorker = channel.unary_unary(
                '/gymgui.trainer.TrainerService/RegisterWorker',
                request_serializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.ControlStream = channel.stream_stream(
                '/gymgui.trainer.TrainerService/ControlStream',
                request_serializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.ControlEvent.SerializeToString,
                response_deserializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.ControlEvent.FromString,
                _registered_method=True)
        self.GetHealth = channel.unary_unary(
                '/gymgui.trainer.TrainerService/GetHealth',
                request_serializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.StreamRunSteps = channel.unary_stream(
                '/gymgui.trainer.TrainerService/StreamRunSteps',
                request_serializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.StreamStepsRequest.SerializeToString,
                response_deserializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.RunStep.FromString,
                _registered_method=True)
        self.StreamRunEpisodes = channel.unary_stream(
                '/gymgui.trainer.TrainerService/StreamRunEpisodes',
                request_serializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.StreamEpisodesRequest.SerializeToString,
                response_deserializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.RunEpisode.FromString,
                _registered_method=True)
        self.PublishRunSteps = channel.stream_unary(
                '/gymgui.trainer.TrainerService/PublishRunSteps',
                request_serializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.RunStep.SerializeToString,
                response_deserializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.PublishTelemetryResponse.FromString,
                _registered_method=True)
        self.PublishRunEpisodes = channel.stream_unary(
                '/gymgui.trainer.TrainerService/PublishRunEpisodes',
                request_serializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.RunEpisode.SerializeToString,
                response_deserializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.PublishTelemetryResponse.FromString,
                _registered_method=True)


class TrainerServiceServicer(object):
    """RPC surface for the trainer daemon.
    """

    def SubmitRun(self, request, context):
        """Registers a new training run and returns the canonical digest.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRun(self, request, context):
        """Cancels an in-flight run. No-op if the run already finished.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRuns(self, request, context):
        """Returns a snapshot of runs filtered by status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchRuns(self, request, context):
        """Streams updates for active runs. Yields whenever a run changes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Worker heartbeat hook to keep the run marked as healthy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWorker(self, request, context):
        """Worker capability handshake that must succeed before telemetry streams start.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControlStream(self, request_iterator, context):
        """Bidirectional control-plane stream for credit grants and pause/resume flow.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHealth(self, request, context):
        """Lightweight daemon heartbeat so the GUI can report liveness.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRunSteps(self, request, context):
        """Streams telemetry step records for the requested run.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRunEpisodes(self, request, context):
        """Streams telemetry episode rollups for the requested run.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishRunSteps(self, request_iterator, context):
        """Worker-side ingestion stream for step telemetry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishRunEpisodes(self, request_iterator, context):
        """Worker-side ingestion stream for episode telemetry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitRun': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitRun,
                    request_deserializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.SubmitRunRequest.FromString,
                    response_serializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.SubmitRunResponse.SerializeToString,
            ),
            'CancelRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRun,
                    request_deserializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.CancelRunRequest.FromString,
                    response_serializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.CancelRunResponse.SerializeToString,
            ),
            'ListRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRuns,
                    request_deserializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.ListRunsRequest.FromString,
                    response_serializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.ListRunsResponse.SerializeToString,
            ),
            'WatchRuns': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchRuns,
                    request_deserializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.WatchRunsRequest.FromString,
                    response_serializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.RunRecord.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.HeartbeatRequest.FromString,
                    response_serializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.HeartbeatResponse.SerializeToString,
            ),
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'ControlStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ControlStream,
                    request_deserializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.ControlEvent.FromString,
                    response_serializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.ControlEvent.SerializeToString,
            ),
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.HealthCheckRequest.FromString,
                    response_serializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.HealthCheckResponse.SerializeToString,
            ),
            'StreamRunSteps': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRunSteps,
                    request_deserializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.StreamStepsRequest.FromString,
                    response_serializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.RunStep.SerializeToString,
            ),
            'StreamRunEpisodes': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRunEpisodes,
                    request_deserializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.StreamEpisodesRequest.FromString,
                    response_serializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.RunEpisode.SerializeToString,
            ),
            'PublishRunSteps': grpc.stream_unary_rpc_method_handler(
                    servicer.PublishRunSteps,
                    request_deserializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.RunStep.FromString,
                    response_serializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.PublishTelemetryResponse.SerializeToString,
            ),
            'PublishRunEpisodes': grpc.stream_unary_rpc_method_handler(
                    servicer.PublishRunEpisodes,
                    request_deserializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.RunEpisode.FromString,
                    response_serializer=gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.PublishTelemetryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gymgui.trainer.TrainerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gymgui.trainer.TrainerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrainerService(object):
    """RPC surface for the trainer daemon.
    """

    @staticmethod
    def SubmitRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gymgui.trainer.TrainerService/SubmitRun',
            gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.SubmitRunRequest.SerializeToString,
            gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.SubmitRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gymgui.trainer.TrainerService/CancelRun',
            gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.CancelRunRequest.SerializeToString,
            gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.CancelRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gymgui.trainer.TrainerService/ListRuns',
            gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.ListRunsRequest.SerializeToString,
            gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.ListRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gymgui.trainer.TrainerService/WatchRuns',
            gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.WatchRunsRequest.SerializeToString,
            gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.RunRecord.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gymgui.trainer.TrainerService/Heartbeat',
            gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.HeartbeatRequest.SerializeToString,
            gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gymgui.trainer.TrainerService/RegisterWorker',
            gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.RegisterWorkerRequest.SerializeToString,
            gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControlStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/gymgui.trainer.TrainerService/ControlStream',
            gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.ControlEvent.SerializeToString,
            gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.ControlEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gymgui.trainer.TrainerService/GetHealth',
            gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.HealthCheckRequest.SerializeToString,
            gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRunSteps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gymgui.trainer.TrainerService/StreamRunSteps',
            gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.StreamStepsRequest.SerializeToString,
            gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.RunStep.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRunEpisodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/gymgui.trainer.TrainerService/StreamRunEpisodes',
            gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.StreamEpisodesRequest.SerializeToString,
            gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.RunEpisode.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishRunSteps(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/gymgui.trainer.TrainerService/PublishRunSteps',
            gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.RunStep.SerializeToString,
            gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.PublishTelemetryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishRunEpisodes(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/gymgui.trainer.TrainerService/PublishRunEpisodes',
            gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.RunEpisode.SerializeToString,
            gym__gui_dot_services_dot_trainer_dot_proto_dot_trainer__pb2.PublishTelemetryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
