"""Documentation for ALE Ice Hockey (2-Player)."""
from __future__ import annotations

ICE_HOCKEY_HTML = (
    "<h3>ALE: Ice Hockey (2-Player)</h3>"
    "<p>Fast-paced two-player ice hockey. Each player controls a team trying to "
    "score goals. Features skating, passing, shooting, and checking mechanics.</p>"
    "<h4>Make (Two-Player)</h4>"
    "<pre><code>from pettingzoo.atari import ice_hockey_v2\n"
    "env = ice_hockey_v2.parallel_env()</code></pre>"
    "<h4>Players</h4>"
    "<ul>"
    "<li><strong>Number of agents:</strong> 2</li>"
    "<li><strong>Agent IDs:</strong> <code>first_0</code>, <code>second_0</code></li>"
    "</ul>"
    "<h4>Action Space</h4>"
    "<p><code>Discrete(18)</code> - Full Atari action set including:</p>"
    "<ul>"
    "<li>Skate in 8 directions</li>"
    "<li>Shoot/check (fire button)</li>"
    "<li>Combined skating + shooting</li>"
    "</ul>"
    "<h4>Observation Space</h4>"
    "<p><code>Box(0, 255, (210, 160, 3), uint8)</code> - RGB image</p>"
    "<h4>Game Mechanics</h4>"
    "<ul>"
    "<li>Control active player on your team</li>"
    "<li>Pass the puck between teammates</li>"
    "<li>Shoot on goal to score</li>"
    "<li>Body check opponents to steal puck</li>"
    "</ul>"
    "<h4>Rewards (Zero-Sum)</h4>"
    "<ul>"
    "<li>Score a goal: <strong>+1</strong> reward</li>"
    "<li>Opponent scores: <strong>-1</strong> reward</li>"
    "</ul>"
    "<h4>Game Type</h4>"
    "<p><strong>Competitive</strong> - Team hockey action.</p>"
    "<p>Docs: <a href='https://pettingzoo.farama.org/environments/atari/ice_hockey/'>"
    "PettingZoo: Ice Hockey</a></p>"
)

__all__ = ["ICE_HOCKEY_HTML"]
