"""Documentation for ALE Othello (2-Player)."""
from __future__ import annotations

OTHELLO_HTML = (
    "<h3>ALE: Othello/Reversi (2-Player)</h3>"
    "<p>Classic Reversi board game. Place pieces to flip your opponent's discs. "
    "The player with the most discs at the end wins. Strategic edge and corner "
    "control is key.</p>"
    "<h4>Make (Two-Player)</h4>"
    "<pre><code>from pettingzoo.atari import othello_v3\n"
    "env = othello_v3.parallel_env()</code></pre>"
    "<h4>Players</h4>"
    "<ul>"
    "<li><strong>Number of agents:</strong> 2</li>"
    "<li><strong>Agent IDs:</strong> <code>first_0</code>, <code>second_0</code></li>"
    "</ul>"
    "<h4>Action Space</h4>"
    "<p><code>Discrete(65)</code></p>"
    "<ul>"
    "<li>Actions 0-63: Place piece on board positions (8x8 grid)</li>"
    "<li>Action 64: Pass turn (when no valid moves)</li>"
    "</ul>"
    "<h4>Observation Space</h4>"
    "<p><code>Box(0, 255, (210, 160, 3), uint8)</code> - RGB image</p>"
    "<h4>Game Mechanics</h4>"
    "<ul>"
    "<li>Place a piece to outflank opponent's pieces</li>"
    "<li>All outflanked pieces flip to your color</li>"
    "<li>Must make a valid capture or pass</li>"
    "<li>Game ends when board is full or no valid moves</li>"
    "</ul>"
    "<h4>Rewards</h4>"
    "<ul>"
    "<li>Flip opponent's pieces: <strong>+N</strong> for N pieces flipped</li>"
    "<li>Win game: final reward based on piece difference</li>"
    "</ul>"
    "<h4>Strategy</h4>"
    "<ul>"
    "<li>Control corners - they cannot be flipped</li>"
    "<li>Avoid edges near empty corners</li>"
    "<li>Maximize stable pieces</li>"
    "</ul>"
    "<h4>Game Type</h4>"
    "<p><strong>Competitive</strong> - Turn-based strategy.</p>"
    "<p>Docs: <a href='https://pettingzoo.farama.org/environments/atari/othello/'>"
    "PettingZoo: Othello</a></p>"
)

__all__ = ["OTHELLO_HTML"]
