"""Documentation for ALE Entombed: Cooperative (2-Player)."""
from __future__ import annotations

ENTOMBED_COOPERATIVE_HTML = (
    "<h3>ALE: Entombed Cooperative (2-Player)</h3>"
    "<p>A cooperative exploration game where you work with your teammate to make it "
    "as far as possible into a constantly generating maze. Navigate together while "
    "avoiding zombies and using power-ups strategically.</p>"
    "<h4>Make (Two-Player)</h4>"
    "<pre><code>from pettingzoo.atari import entombed_cooperative_v3\n"
    "env = entombed_cooperative_v3.parallel_env()</code></pre>"
    "<h4>Players</h4>"
    "<ul>"
    "<li><strong>Number of agents:</strong> 2</li>"
    "<li><strong>Agent IDs:</strong> <code>first_0</code>, <code>second_0</code></li>"
    "</ul>"
    "<h4>Action Space</h4>"
    "<p><code>Discrete(18)</code> - Full Atari action set including:</p>"
    "<ul>"
    "<li>Movement in 8 directions</li>"
    "<li>Fire actions in various directions</li>"
    "<li>No operation</li>"
    "</ul>"
    "<h4>Observation Space</h4>"
    "<p><code>Box(0, 255, (210, 160, 3), uint8)</code> - RGB image</p>"
    "<h4>Game Mechanics</h4>"
    "<ul>"
    "<li>Progress through five invisible maze sections sequentially</li>"
    "<li>Rare power-ups break through walls symmetrically (both screen halves)</li>"
    "<li>Optimal play requires agents on opposite sides to access power-ups</li>"
    "<li>Avoid zombies throughout the maze</li>"
    "<li>Dead-ends escapable only through power-up usage</li>"
    "</ul>"
    "<h4>Rewards</h4>"
    "<p>Identical to single-player rewards. Players receive immediate rewards after "
    "advancing sections or resetting stages. Reward is given when losing a life (stage reset) "
    "but not when losing the final life (game termination).</p>"
    "<p><strong>Average Total Reward:</strong> 6.23</p>"
    "<h4>Game Type</h4>"
    "<p><strong>Cooperative</strong> - Work together to progress as far as possible.</p>"
    "<p>Docs: <a href='https://pettingzoo.farama.org/environments/atari/entombed_cooperative/'>"
    "PettingZoo: Entombed Cooperative</a></p>"
)

__all__ = ["ENTOMBED_COOPERATIVE_HTML"]
