"""Documentation for MiniGrid Empty Room environments."""
from __future__ import annotations

MINIGRID_EMPTY_HTML = (
    "<h3>MiniGrid Empty Room Family</h3>"
    "<p>Empty rooms with a green goal tile. No obstacles — ideal for debugging observation pipelines, testing sparse reward handling, and validating agent navigation. "
    "The <strong>Random</strong> variants randomize agent starting position each episode.</p>"
    "<h4>Variants</h4>"
    "<ul>"
    "<li><strong>5x5</strong> — Tiny room (fixed start)</li>"
    "<li><strong>5x5-Random</strong> — Tiny room (random start)</li>"
    "<li><strong>6x6</strong> — Small room (fixed start)</li>"
    "<li><strong>6x6-Random</strong> — Small room (random start)</li>"
    "<li><strong>8x8</strong> — Medium room (fixed start)</li>"
    "<li><strong>16x16</strong> — Large room for exploration experiments (fixed start)</li>"
    "</ul>"
    "<h4>Observation</h4>"
    "<p>Dict observation with <code>image</code> (RGB, 7×7×3), <code>direction</code> (0=right,1=down,2=left,3=up) and <code>mission</code> text. The GUI flattens this to a uint8 vector while keeping the RGB frame for rendering.</p>"
    "<h4>Rewards</h4>"
    "<ul>"
    "<li>Success → <code>1 - 0.9 * (step_count / max_steps)</code> (scaled by reward multiplier, default ×10)</li>"
    "<li>Otherwise → 0</li>"
    "</ul>"
    "<h4>Episode end</h4>"
    "<ul>"
    "<li>Termination: agent reaches the goal tile</li>"
    "<li>Truncation: max_episode_steps timeout</li>"
    "</ul>"
    "<h4>Action space (Discrete(7))</h4>"
    "<ul>"
    "<li>0 → turn left</li>"
    "<li>1 → turn right</li>"
    "<li>2 → move forward</li>"
    "<li>3 → pick up (unused)</li>"
    "<li>4 → drop (unused)</li>"
    "<li>5 → toggle / interact (unused)</li>"
    "<li>6 → done (no-op)</li>"
    "</ul>"
    "<p><strong>Keyboard:</strong> ←/A, →/D, ↑/W, Space/G (pick up), H (drop), E/Enter (toggle), Q (done).</p>"
    "<p>See the docs: <a href=\"https://minigrid.farama.org/environments/minigrid/EmptyEnv/\">MiniGrid Empty Room</a></p>"
)

__all__ = ["MINIGRID_EMPTY_HTML"]
