"""Documentation for ALE Boxing (2-Player)."""
from __future__ import annotations

BOXING_HTML = (
    "<h3>ALE: Boxing (2-Player)</h3>"
    "<p>Two-player boxing match where players control boxers in a top-down view. "
    "Land punches on your opponent to score points. Strategic positioning and timing "
    "are key to victory.</p>"
    "<h4>Make (Two-Player)</h4>"
    "<pre><code>from pettingzoo.atari import boxing_v2\n"
    "env = boxing_v2.parallel_env()</code></pre>"
    "<h4>Players</h4>"
    "<ul>"
    "<li><strong>Number of agents:</strong> 2</li>"
    "<li><strong>Agent IDs:</strong> <code>first_0</code>, <code>second_0</code></li>"
    "</ul>"
    "<h4>Action Space</h4>"
    "<p><code>Discrete(18)</code> - Full Atari action set including:</p>"
    "<ul>"
    "<li>Movement in 8 directions</li>"
    "<li>Punch (fire button)</li>"
    "<li>Combined movement + punch actions</li>"
    "</ul>"
    "<h4>Observation Space</h4>"
    "<p><code>Box(0, 255, (210, 160, 3), uint8)</code> - RGB image</p>"
    "<h4>Game Mechanics</h4>"
    "<ul>"
    "<li>Move your boxer to position for attacks</li>"
    "<li>Press fire + direction to punch</li>"
    "<li>Each landed punch scores 1 point</li>"
    "<li>Match ends after 2-minute time limit</li>"
    "</ul>"
    "<h4>Rewards (Zero-Sum)</h4>"
    "<ul>"
    "<li>Land a punch: <strong>+1</strong> reward</li>"
    "<li>Get punched: <strong>-1</strong> reward</li>"
    "</ul>"
    "<h4>Game Type</h4>"
    "<p><strong>Competitive</strong> - Land more punches than your opponent.</p>"
    "<p>Docs: <a href='https://pettingzoo.farama.org/environments/atari/boxing/'>"
    "PettingZoo: Boxing</a></p>"
)

__all__ = ["BOXING_HTML"]
