"""Utilities for validating CleanRL worker configurations via dry-run."""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Dict, Tuple


def _merge_output(stdout: Any, stderr: Any) -> str:
    parts: list[str] = []
    for chunk in (stdout, stderr):
        if not chunk:
            continue
        if isinstance(chunk, bytes):
            parts.append(chunk.decode("utf-8", errors="replace"))
        else:
            parts.append(str(chunk))
    return "".join(parts)


def run_cleanrl_dry_run(
    config_payload: Dict[str, Any],
    *,
    timeout_seconds: int = 120,
) -> Tuple[bool, str]:
    """Execute ``cleanrl_worker.cli`` in ``--dry-run`` mode to validate a payload.

    Args:
        config_payload: Trainer configuration dictionary generated by the CleanRL form.
        timeout_seconds: Maximum time to wait for the subprocess to finish.

    Returns:
        Tuple where the first element indicates success and the second contains the
        combined stdout/stderr from the dry-run attempt.
    """

    with tempfile.TemporaryDirectory(prefix="cleanrl-dry-run-") as tmp_dir:
        config_path = Path(tmp_dir) / "config.json"
        config_path.write_text(json.dumps(config_payload, indent=2), encoding="utf-8")

        command = [
            sys.executable,
            "-m",
            "cleanrl_worker.cli",
            "--config",
            str(config_path),
            "--dry-run",
            "--emit-summary",
        ]

        env = os.environ.copy()
        try:
            result = subprocess.run(
                command,
                capture_output=True,
                text=True,
                check=False,
                timeout=timeout_seconds,
                env=env,
            )
        except subprocess.TimeoutExpired as exc:  # pragma: no cover - defensive
            output = _merge_output(exc.stdout, exc.stderr)
            return False, output or "CleanRL dry-run timed out"

    output = _merge_output(result.stdout, result.stderr)
    success = result.returncode == 0
    if not success and not output:
        output = "CleanRL dry-run failed without output."
    return success, output


__all__ = ["run_cleanrl_dry_run"]
