"""Utilities for validating XuanCe worker configurations via dry-run."""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Dict, Tuple


def _merge_output(stdout: Any, stderr: Any) -> str:
    """Merge stdout and stderr into a single string."""
    parts: list[str] = []
    for chunk in (stdout, stderr):
        if not chunk:
            continue
        if isinstance(chunk, bytes):
            parts.append(chunk.decode("utf-8", errors="replace"))
        else:
            parts.append(str(chunk))
    return "".join(parts)


def run_xuance_dry_run(
    config_payload: Dict[str, Any],
    *,
    timeout_seconds: int = 120,
) -> Tuple[bool, str]:
    """Execute ``xuance_worker.cli`` in ``--dry-run`` mode to validate a payload.

    This function spawns a subprocess to validate the XuanCe worker configuration
    without actually running training. It validates:
    - Configuration file syntax and required fields
    - Environment availability (import checks)
    - Algorithm compatibility with selected environment

    Args:
        config_payload: Trainer configuration dictionary generated by the XuanCe form.
            Should contain the worker config with method, env, env_id, etc.
        timeout_seconds: Maximum time to wait for the subprocess to finish.

    Returns:
        Tuple where the first element indicates success (True if validation passed)
        and the second contains the combined stdout/stderr from the dry-run attempt.

    Example:
        >>> config = {
        ...     "method": "PPO_Clip",
        ...     "env": "classic_control",
        ...     "env_id": "CartPole-v1",
        ...     "running_steps": 10000,
        ... }
        >>> success, output = run_xuance_dry_run(config)
        >>> if success:
        ...     print("Configuration valid!")
        ... else:
        ...     print(f"Validation failed: {output}")
    """

    with tempfile.TemporaryDirectory(prefix="xuance-dry-run-") as tmp_dir:
        config_path = Path(tmp_dir) / "config.json"
        config_path.write_text(json.dumps(config_payload, indent=2), encoding="utf-8")

        command = [
            sys.executable,
            "-m",
            "xuance_worker.cli",
            "--config",
            str(config_path),
            "--dry-run",
            "--emit-summary",
        ]

        env = os.environ.copy()
        try:
            result = subprocess.run(
                command,
                capture_output=True,
                text=True,
                check=False,
                timeout=timeout_seconds,
                env=env,
            )
        except subprocess.TimeoutExpired as exc:  # pragma: no cover - defensive
            output = _merge_output(exc.stdout, exc.stderr)
            return False, output or "XuanCe dry-run timed out"

    output = _merge_output(result.stdout, result.stderr)
    success = result.returncode == 0
    if not success and not output:
        output = "XuanCe dry-run failed without output."
    return success, output


__all__ = ["run_xuance_dry_run"]
