"""Utilities for validating CleanRL worker configurations via dry-run."""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Dict, Tuple


def _merge_output(stdout: Any, stderr: Any) -> str:
    parts: list[str] = []
    for chunk in (stdout, stderr):
        if not chunk:
            continue
        if isinstance(chunk, bytes):
            parts.append(chunk.decode("utf-8", errors="replace"))
        else:
            parts.append(str(chunk))
    return "".join(parts)


def run_cleanrl_dry_run(
    config_payload: Dict[str, Any],
    *,
    timeout_seconds: int = 120,
) -> Tuple[bool, str]:
    """Execute ``cleanrl_worker.cli`` in ``--dry-run`` mode to validate a payload.

    Args:
        config_payload: Trainer configuration dictionary generated by the CleanRL form.
        timeout_seconds: Maximum time to wait for the subprocess to finish.

    Returns:
        Tuple where the first element indicates success and the second contains the
        combined stdout/stderr from the dry-run attempt.
    """

    with tempfile.TemporaryDirectory(prefix="cleanrl-dry-run-") as tmp_dir:
        config_path = Path(tmp_dir) / "config.json"
        config_path.write_text(json.dumps(config_payload, indent=2), encoding="utf-8")

        command = [
            sys.executable,
            "-m",
            "cleanrl_worker.cli",
            "--config",
            str(config_path),
            "--dry-run",
            "--emit-summary",
        ]

        # Set FastLane environment variables from config payload
        # These are needed because fastlane.py reads them at module import time
        env = os.environ.copy()

        # First, try to get environment variables from the top-level "environment" key
        # (the canonical location set by the form via apply_fastlane_environment)
        top_level_env = config_payload.get("environment", {}) or {}
        for key, value in top_level_env.items():
            if value is not None:
                env[str(key)] = str(value)

        # Also extract from metadata.worker.config.extras for backwards compatibility
        # and to get algo_params
        worker_config = (
            config_payload.get("metadata", {})
            .get("worker", {})
            .get("config", {})
        )
        extras = worker_config.get("extras", {}) or {}
        algo_params = extras.get("algo_params", {}) or {}

        # Map fastlane config from payload to environment variables (if not already set)
        # Use setdefault to prefer values from top-level environment dict
        fastlane_only = extras.get("fastlane_only")
        if fastlane_only is not None:
            env.setdefault("GYM_GUI_FASTLANE_ONLY", "1" if fastlane_only else "0")

        fastlane_slot = extras.get("fastlane_slot")
        if fastlane_slot is not None:
            env.setdefault("GYM_GUI_FASTLANE_SLOT", str(fastlane_slot))

        fastlane_video_mode = extras.get("fastlane_video_mode")
        if fastlane_video_mode is not None:
            env.setdefault("GYM_GUI_FASTLANE_VIDEO_MODE", str(fastlane_video_mode))

        fastlane_grid_limit = extras.get("fastlane_grid_limit")
        if fastlane_grid_limit is not None:
            env.setdefault("GYM_GUI_FASTLANE_GRID_LIMIT", str(fastlane_grid_limit))

        # Set run_id for FastLane buffer naming
        run_id = worker_config.get("run_id") or config_payload.get("run_id")
        if run_id:
            env.setdefault("CLEANRL_RUN_ID", str(run_id))

        # Set num_envs for grid limit calculations
        num_envs = algo_params.get("num_envs")
        if num_envs is not None:
            env.setdefault("CLEANRL_NUM_ENVS", str(num_envs))
        try:
            result = subprocess.run(
                command,
                capture_output=True,
                text=True,
                check=False,
                timeout=timeout_seconds,
                env=env,
            )
        except subprocess.TimeoutExpired as exc:  # pragma: no cover - defensive
            output = _merge_output(exc.stdout, exc.stderr)
            return False, output or "CleanRL dry-run timed out"

    output = _merge_output(result.stdout, result.stderr)
    success = result.returncode == 0
    if not success and not output:
        output = "CleanRL dry-run failed without output."
    return success, output


__all__ = ["run_cleanrl_dry_run"]
