"""Documentation for Overcooked Counter Circuit layout."""
from __future__ import annotations


def get_counter_circuit_html(env_id: str) -> str:
    """Generate Counter Circuit HTML documentation."""
    return (
        f"<h2>{env_id}</h2>"
        "<p>A circuit-based kitchen with a <strong>hidden optimal strategy</strong>: passing onions over counters as relay points instead of carrying them around the long circuit. Tests strategy discovery and creative problem-solving.</p>"
        "<h4>Layout Characteristics</h4>"
        "<ul>"
        "<li><strong>Difficulty:</strong> ⭐⭐⭐⭐⭐ (Expert)</li>"
        "<li><strong>Challenge:</strong> Non-obvious coordination strategy discovery</li>"
        "<li><strong>SP-XP Gap:</strong> ⚠ SIGNIFICANT (different counter protocols)</li>"
        "<li><strong>Best for:</strong> Testing exploration and creative strategy innovation</li>"
        "</ul>"
        "<h4>The Strategic Revelation</h4>"
        "<p>The layout presents two approaches with dramatically different performance:</p>"
        "<ul>"
        "<li><strong>Naive Strategy (Obvious):</strong> Carry onions around full circuit → Slow (~100-140 points)</li>"
        "<li><strong>Optimal Strategy (Hidden):</strong> Pass onions via counter relay → Fast (~220-280 points)</li>"
        "</ul>"
        "<p>⚠ <strong>Discovery Challenge:</strong> Agents must LEARN that counters can be relay points, not just storage!</p>"
        "<h4>Optimal Strategy: Counter-Relay Pipeline</h4>"
        "<ol>"
        "<li><strong>Agent A (near onions):</strong> Get onion → Place on designated relay counter → Immediately get next</li>"
        "<li><strong>Agent B (near pot):</strong> Monitor relay counter → Pick up onions → Place in pot (3 total)</li>"
        "<li><strong>Result:</strong> Counter acts as asynchronous buffer, eliminating long circuit travel</li>"
        "</ol>"
        "<h4>Coordination Requirements</h4>"
        "<ul>"
        "<li>Discover counter-passing strategy exists (exploration!)</li>"
        "<li>Agree on WHICH counter(s) to use as relay</li>"
        "<li>Synchronize placing/picking timing</li>"
        "<li>Understand circuit topology and shortcuts</li>"
        "</ul>"
        "<h4>Common Failure Modes</h4>"
        "<ul>"
        "<li>⚠⚠⚠ <strong>Never discovering strategy:</strong> Agents with sparse exploration stuck with naive approach forever</li>"
        "<li>Inconsistent usage: Sometimes uses counters, sometimes doesn't → unpredictable</li>"
        "<li>Wrong counter selection: Uses counter far from optimal relay point → no benefit</li>"
        "<li>Counter clutter: Multiple items block workflow</li>"
        "<li>SP-XP gap: Different populations use different counter conventions</li>"
        "</ul>"
        "<h4>Performance Benchmarks (400 timesteps)</h4>"
        "<ul>"
        "<li>Naive circuit carry: ~100-140 points (5-7 soups)</li>"
        "<li>Partial counter usage: ~140-180 points (7-9 soups)</li>"
        "<li>Optimal counter relay (self-play): ~220-260 points (11-13 soups)</li>"
        "<li>⚠ Optimal (cross-play with different protocol): ~160-220 points (SP-XP gap!)</li>"
        "<li>Human-human (with discovery): ~240-280 points (12-14 soups)</li>"
        "</ul>"
        "<h4>Research Context</h4>"
        "<p>Counter Circuit is the <strong>ultimate test of exploration and strategy innovation</strong>. Unlike other layouts with obvious solutions, this requires creative problem-solving.</p>"
        "<p><strong>Key Finding:</strong> \"Reveals the importance of strategy discovery in coordination. Agents that only execute known strategies (not discover new ones) fail when creative solutions are needed.\"</p>"
        "<p><strong>Performance Tiers:</strong></p>"
        "<ol>"
        "<li>No discovery: ~100-140 points (naive)</li>"
        "<li>Individual discovery: ~140-180 points (inconsistent)</li>"
        "<li>Joint protocol: ~220-260 points (coordinated relay)</li>"
        "</ol>"
        "<p><strong>Real-World Analogy:</strong> Like discovering that passing documents over a cubicle wall is faster than walking around the office. Creative solutions dramatically outperform obvious ones.</p>"
        "<p>See: <a href=\"https://github.com/HumanCompatibleAI/overcooked_ai\">Overcooked-AI Repository</a> | <a href=\"https://arxiv.org/abs/1910.05789\">Research Paper</a></p>"
    )


# For backward compatibility
OVERCOOKED_COUNTER_CIRCUIT_HTML = get_counter_circuit_html("overcooked/counter_circuit")

__all__ = ["OVERCOOKED_COUNTER_CIRCUIT_HTML", "get_counter_circuit_html"]
