"""Documentation for ALE Flag Capture (2-Player)."""
from __future__ import annotations

FLAG_CAPTURE_HTML = (
    "<h3>ALE: Flag Capture (2-Player)</h3>"
    "<p>A battle of memory and information. Players search a map to find a hidden flag "
    "while gathering clues from exploration and observing opponent actions.</p>"
    "<h4>Make (Two-Player)</h4>"
    "<pre><code>from pettingzoo.atari import flag_capture_v2\n"
    "env = flag_capture_v2.parallel_env()</code></pre>"
    "<h4>Players</h4>"
    "<ul>"
    "<li><strong>Number of agents:</strong> 2</li>"
    "<li><strong>Agent IDs:</strong> <code>first_0</code>, <code>second_0</code></li>"
    "</ul>"
    "<h4>Action Space</h4>"
    "<p><code>Discrete(10)</code></p>"
    "<ul>"
    "<li>0: No operation</li>"
    "<li>1: Fire</li>"
    "<li>2-5: Move in cardinal directions (up, right, left, down)</li>"
    "<li>6-9: Move diagonally (upright, upleft, downright, downleft)</li>"
    "</ul>"
    "<h4>Observation Space</h4>"
    "<p><code>Box(0, 255, (210, 160, 3), uint8)</code> - RGB image</p>"
    "<h4>Game Mechanics</h4>"
    "<ul>"
    "<li>Traverse the map checking squares to find the hidden flag</li>"
    "<li>Finding the flag grants a point to the finder and penalizes the opponent</li>"
    "<li>Landing on a bomb returns you to your starting position</li>"
    "<li>Other squares provide directional or distance hints about the flag's location</li>"
    "<li>Success requires synthesizing information from exploration and opponent movements</li>"
    "</ul>"
    "<h4>Rewards</h4>"
    "<ul>"
    "<li>Find the flag: <strong>+1</strong> reward</li>"
    "<li>Opponent finds flag: <strong>-1</strong> reward</li>"
    "</ul>"
    "<h4>Game Type</h4>"
    "<p><strong>Competitive</strong> - Race to find the hidden flag first.</p>"
    "<p>Docs: <a href='https://pettingzoo.farama.org/environments/atari/flag_capture/'>"
    "PettingZoo: Flag Capture</a></p>"
)

__all__ = ["FLAG_CAPTURE_HTML"]
