"""Documentation for PettingZoo Tic-Tac-Toe."""
from __future__ import annotations


def get_tictactoe_html(env_id: str = "tictactoe_v3") -> str:
    """Generate Tic-Tac-Toe HTML documentation."""
    return (
        "<h3>PettingZoo: Tic-Tac-Toe (tictactoe_v3)</h3>"
        "<p>Classic Tic-Tac-Toe game where 2 players, X and O, take turns marking "
        "spaces on a 3×3 grid. The first player to place 3 of their marks in a "
        "horizontal, vertical, or diagonal line wins.</p>"
        "<h4>Environment Details</h4>"
        "<ul>"
        "<li><strong>Import:</strong> <code>from pettingzoo.classic import tictactoe_v3</code></li>"
        "<li><strong>API Type:</strong> AEC (turn-based)</li>"
        "<li><strong>Parallel API:</strong> Yes</li>"
        "<li><strong>Agents:</strong> ['player_1', 'player_2']</li>"
        "<li><strong>Action Shape:</strong> Discrete(9)</li>"
        "<li><strong>Action Values:</strong> [0, 8]</li>"
        "<li><strong>Observation Shape:</strong> (3, 3, 2)</li>"
        "<li><strong>Observation Values:</strong> [0, 1]</li>"
        "</ul>"
        "<h4>Observation Space</h4>"
        "<p>3×3×2 binary tensor representing the board state:</p>"
        "<ul>"
        "<li><strong>Channel 0:</strong> Current player's marks (1 where player has X/O)</li>"
        "<li><strong>Channel 1:</strong> Opponent's marks (1 where opponent has X/O)</li>"
        "</ul>"
        "<p>For player_1, channel 0 shows Xs and channel 1 shows Os. "
        "For player_2, the planes are swapped to enable self-play.</p>"
        "<h4>Action Space</h4>"
        "<p>Discrete(9) - each action places a mark in the corresponding cell:</p>"
        "<pre>"
        "0 | 3 | 6\n"
        "---------\n"
        "1 | 4 | 7\n"
        "---------\n"
        "2 | 5 | 8"
        "</pre>"
        "<p>Note: The indexing is column-major (action 0 is top-left, action 2 is bottom-left).</p>"
        "<h4>Legal Actions Mask</h4>"
        "<p>The <code>observation['action_mask']</code> is a binary vector of length 9. "
        "A cell is legal (mask=1) if it's empty. Taking an illegal action "
        "ends the game with -1 reward for the illegal mover and 0 for the opponent.</p>"
        "<h4>Rewards</h4>"
        "<table>"
        "<tr><th>Winner</th><th>Loser</th><th>Draw</th></tr>"
        "<tr><td>+1</td><td>-1</td><td>0</td></tr>"
        "</table>"
        "<p>Rewards are given at game end. Draw occurs when board is full with no winner.</p>"
        "<h4>Usage (AEC)</h4>"
        "<pre><code>from pettingzoo.classic import tictactoe_v3\n\n"
        "env = tictactoe_v3.env(render_mode='human')\n"
        "env.reset(seed=42)\n\n"
        "for agent in env.agent_iter():\n"
        "    observation, reward, termination, truncation, info = env.last()\n\n"
        "    if termination or truncation:\n"
        "        action = None\n"
        "    else:\n"
        "        mask = observation['action_mask']\n"
        "        action = env.action_space(agent).sample(mask)\n\n"
        "    env.step(action)\n"
        "env.close()</code></pre>"
        "<h4>Human Control Mode</h4>"
        "<p>In the GUI, click on a cell to place your mark. The game alternates between "
        "player_1 (X) and player_2 (O). Invalid moves are rejected.</p>"
        "<h4>Version History</h4>"
        "<ul>"
        "<li><strong>v3:</strong> Fixed bug in arbitrary calls to observe() (1.8.0)</li>"
        "<li><strong>v2:</strong> Legal action mask in observation replaced illegal move list in infos (1.5.0)</li>"
        "<li><strong>v1:</strong> Bumped version for all envs (1.4.0)</li>"
        "<li><strong>v0:</strong> Initial release (1.0.0)</li>"
        "</ul>"
        "<p>Docs: <a href='https://pettingzoo.farama.org/environments/classic/tictactoe/'>PettingZoo Tic-Tac-Toe</a></p>"
    )


# For backward compatibility
TICTACTOE_HTML = get_tictactoe_html()

__all__ = ["TICTACTOE_HTML", "get_tictactoe_html"]
