"""Documentation for PettingZoo SISL Waterworld environment."""
from __future__ import annotations


def get_waterworld_html(env_id: str = "waterworld_v4") -> str:
    """Generate Waterworld environment HTML documentation."""
    return (
        "<h3>PettingZoo SISL: Waterworld (waterworld_v4)</h3>"
        "<p>Simulation of archea navigating and surviving. Pursuers (agents) attempt to consume "
        "food while avoiding poison. Multiple pursuers may need to cooperate to consume food.</p>"
        "<h4>Environment Details</h4>"
        "<ul>"
        "<li><strong>Import:</strong> <code>from pettingzoo.sisl import waterworld_v4</code></li>"
        "<li><strong>Actions:</strong> Continuous</li>"
        "<li><strong>Parallel API:</strong> Yes</li>"
        "<li><strong>Agents:</strong> ['pursuer_0', ..., 'pursuer_4'] (default 5)</li>"
        "<li><strong>Action Shape:</strong> (2,) - [horizontal_thrust, vertical_thrust]</li>"
        "<li><strong>Action Values:</strong> [-0.01, 0.01]</li>"
        "<li><strong>Observation Shape:</strong> (242,) with 30 sensors</li>"
        "</ul>"
        "<h4>Observation Space</h4>"
        "<p>Vector of sensor readings (8 features per sensor by default):</p>"
        "<ul>"
        "<li>Obstacle distance, Barrier distance, Food distance/speed</li>"
        "<li>Poison distance/speed, Pursuer distance/speed</li>"
        "<li>Collision indicators (food/poison)</li>"
        "</ul>"
        "<h4>Rewards</h4>"
        "<ul>"
        "<li><strong>food_reward:</strong> +10 when n_coop agents touch food</li>"
        "<li><strong>encounter_reward:</strong> +0.01 for touching food</li>"
        "<li><strong>poison_reward:</strong> -1 for touching poison</li>"
        "<li><strong>thrust_penalty:</strong> -0.5 × ||action|| per step</li>"
        "</ul>"
        "<h4>Key Arguments</h4>"
        "<pre><code>waterworld_v4.env(\n"
        "    n_pursuers=5,      # Number of agents\n"
        "    n_evaders=5,       # Number of food objects\n"
        "    n_poisons=10,      # Number of poison objects\n"
        "    n_coop=2,          # Agents needed to consume food\n"
        "    n_sensors=20,      # Sensors per agent\n"
        "    sensor_range=0.2,  # Sensor range\n"
        "    local_ratio=1.0,   # Local vs global reward distribution\n"
        "    max_cycles=500     # Steps per episode\n"
        ")</code></pre>"
        "<h4>Usage</h4>"
        "<pre><code>from pettingzoo.sisl import waterworld_v4\n\n"
        "env = waterworld_v4.env(render_mode='human')\n"
        "env.reset(seed=42)\n\n"
        "for agent in env.agent_iter():\n"
        "    obs, reward, term, trunc, info = env.last()\n"
        "    action = None if term or trunc else env.action_space(agent).sample()\n"
        "    env.step(action)\n"
        "env.close()</code></pre>"
        "<h4>Version History</h4>"
        "<ul>"
        "<li><strong>v4:</strong> Major refactor (1.22.0)</li>"
        "<li><strong>v3:</strong> Refactor and major bug fixes (1.5.0)</li>"
        "</ul>"
    )


WATERWORLD_HTML = get_waterworld_html()

__all__ = ["WATERWORLD_HTML", "get_waterworld_html"]
