"""Documentation for ALE Space Invaders (2-Player)."""
from __future__ import annotations

SPACE_INVADERS_HTML = (
    "<h3>ALE: Space Invaders (2-Player)</h3>"
    "<p>Two ships controlled by two players defending against alien invasion. "
    "Can coordinate to clear levels or compete for higher scores. Features "
    "unique competitive mechanics.</p>"
    "<h4>Make (Two-Player)</h4>"
    "<pre><code>from pettingzoo.atari import space_invaders_v2\n"
    "env = space_invaders_v2.parallel_env()</code></pre>"
    "<h4>Players</h4>"
    "<ul>"
    "<li><strong>Number of agents:</strong> 2</li>"
    "<li><strong>Agent IDs:</strong> <code>first_0</code>, <code>second_0</code></li>"
    "</ul>"
    "<h4>Action Space</h4>"
    "<p><code>Discrete(6)</code></p>"
    "<ul>"
    "<li>0: No operation</li>"
    "<li>1: Fire</li>"
    "<li>2: Move up</li>"
    "<li>3: Move right</li>"
    "<li>4: Move left</li>"
    "<li>5: Move down</li>"
    "</ul>"
    "<h4>Observation Space</h4>"
    "<p><code>Box(0, 255, (210, 160, 3), uint8)</code> - RGB image</p>"
    "<h4>Game Mechanics</h4>"
    "<ul>"
    "<li>Shoot aliens before they reach the bottom</li>"
    "<li>Hide behind shields for protection</li>"
    "<li>Shoot the mystery ship for bonus points</li>"
    "<li>Shared lives between ships</li>"
    "</ul>"
    "<h4>Rewards</h4>"
    "<ul>"
    "<li>Destroy alien: <strong>+5 to +30</strong> based on position</li>"
    "<li>Mystery ship: <strong>+100</strong> points</li>"
    "<li>Other player hit by aliens: <strong>+200</strong> bonus</li>"
    "</ul>"
    "<h4>Difficulty Parameters</h4>"
    "<ul>"
    "<li>Alternating firing control</li>"
    "<li>Moving shields</li>"
    "<li>Zigzagging bombs</li>"
    "<li>Fast bombs</li>"
    "<li>Invisible invaders</li>"
    "</ul>"
    "<h4>Game Type</h4>"
    "<p><strong>Mixed</strong> - Cooperative or competitive (sabotage possible).</p>"
    "<p>Docs: <a href='https://pettingzoo.farama.org/environments/atari/space_invaders/'>"
    "PettingZoo: Space Invaders</a></p>"
)

__all__ = ["SPACE_INVADERS_HTML"]
